/* ============================================================
   ZIVOZONE APP ENGINE V8
   - Firebase preserved
   - Guest play preserved
   - Unique challenge sessions
   - Mixed question types
   - Continuous challenge-only audio
   - Dark Room infinite psychological mode
============================================================ */
(() => {
  'use strict';
  const A=window.ZIVOZONE_AUTH,C=window.ZIVOZONE_CHALLENGES,I=window.ZIVOZONE_I18N;
  const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)];
  const LS='zivozone_state_v8';
  const API=window.ZIVOZONE_API||{};
  let state={level:1,xp:0,coins:0,wins:0,gamesPlayed:0,identity:null};
  let game={id:null,questions:[],index:0,score:0,answers:[],guest:true,locked:false,horrorSignupShown:false,horrorUsed:[]};
  const t=k=>I.tr(k),lang=()=>I.get(),S=()=>window.ZIVOZONE_AUDIO||{},O=(ar,en)=>({ar,en,zh:en,hi:en,es:en});
  const esc=s=>{const d=document.createElement('div');d.textContent=String(s??'');return d.innerHTML};
  const loc=o=>typeof o==='string'?o:(o?.[lang()]||o?.en||o?.ar||'');
  const toast=(msg,type='info')=>{const box=$('#toast-container');if(!box)return;const x=document.createElement('div');x.className='toast '+type;x.textContent=msg;box.appendChild(x);setTimeout(()=>x.remove(),3200)};
  const loadState=()=>{try{state={...state,...JSON.parse(localStorage.getItem(LS)||'{}')}}catch(e){}};
  const saveState=()=>{state.level=Math.floor((Number(state.xp)||0)/100)+1;try{localStorage.setItem(LS,JSON.stringify(state))}catch(e){}};
  function syncFromPlayer(){const p=A.getPlayer();if(!p)return;state={...state,xp:Number(p.xp)||0,coins:Number(p.coins)||0,wins:Number(p.wins)||0,gamesPlayed:Number(p.gamesPlayed)||0,level:Number(p.level)||1};saveState()}
  function profile(){const p=A.getPlayer(),l=state.level||1,base=(l-1)*100,prog=Math.max(0,Math.min(100,state.xp-base));$('#profile-name').textContent=p?.name||t('guest');$('#profile-email').textContent=p?.email||t('guestText');$('#profile-level').textContent=l;$('#profile-xp').textContent=state.xp;$('#profile-coins').textContent=state.coins;$('#profile-wins').textContent=state.wins;$('#player-level-chip').textContent=`${t('level')} ${l}`;$('#xp-progress').style.width=prog+'%';$('#logout-btn').hidden=!A.isLoggedIn();$('#login-btn').textContent=A.isLoggedIn()?`👤 ${p?.name||t('profile')}`:t('login')}
  async function reward(xp,coins=1,win=true){state.xp+=xp;state.coins+=coins;if(win)state.wins++;state.gamesPlayed++;saveState();if(A.isLoggedIn())await A.update({xp:state.xp,coins:state.coins,wins:state.wins,gamesPlayed:state.gamesPlayed,level:state.level});profile()}
  function closeModal(){const r=$('#modal-root');r.setAttribute('aria-hidden','true');r.innerHTML=''}
  function exitToChallengeCenter(){S().stopChallenge?.();document.body.classList.remove('horror-active');closeModal();location.hash='#challenges';setTimeout(()=>$('#challenges')?.scrollIntoView({behavior:'smooth',block:'start'}),40)}
  function openModal(html,cls=''){const r=$('#modal-root');r.innerHTML=`<div class="modal-backdrop"><div class="modal-card ${cls}" role="dialog" aria-modal="true">${html}</div></div>`;r.setAttribute('aria-hidden','false');r.querySelectorAll('[data-close]').forEach(b=>b.onclick=closeModal);const bg=r.querySelector('.modal-backdrop');if(bg)bg.onclick=e=>{if(e.target===bg)closeModal()}}
  function authModal(after){let mode='register';const render=()=>{openModal(`<button class="modal-close" data-close>×</button><span class="eyebrow">${t('account')}</span><h2>${mode==='register'?t('register'):t('welcomeBack')}</h2><p class="muted">${mode==='register'?t('registerHint'):t('loginHint')}</p><div class="auth-tabs"><button id="tab-register" class="btn ${mode==='register'?'btn-primary':''}">${t('register')}</button><button id="tab-login" class="btn ${mode==='login'?'btn-primary':''}">${t('signIn')}</button></div><form id="auth-form">${mode==='register'?`<div><label>${t('playerName')}</label><input id="auth-name" minlength="2" required placeholder="${esc(t('yourName'))}"></div><div><label>${t('age')}</label><input id="auth-age" type="number" min="5" max="100" required value="18"></div>`:''}<div><label>${t('email')}</label><input id="auth-email" type="email" required placeholder="${esc(t('emailPlaceholder'))}"></div><div><label>${t('password')}</label><input id="auth-pass" type="password" minlength="6" required placeholder="${esc(t('passwordPlaceholder'))}"></div><button class="btn btn-primary full" type="submit">${mode==='register'?t('createAccount'):t('signIn')}</button></form></div>`);$('#tab-register').onclick=()=>{mode='register';render()};$('#tab-login').onclick=()=>{mode='login';render()};$('#auth-form').onsubmit=async e=>{e.preventDefault();try{if(mode==='register')await A.register({name:$('#auth-name').value,age:$('#auth-age').value,email:$('#auth-email').value,password:$('#auth-pass').value});else await A.login($('#auth-email').value,$('#auth-pass').value);await A.setLanguage(lang());closeModal();syncFromPlayer();profile();toast(t('success'),'success');if(after)after()}catch(err){toast(err.message||t('firebaseError'),'error')}}};render()}
  function shuffle(a){a=a.slice();for(let i=a.length-1;i>0;i--){const j=Math.floor(Math.random()*(i+1));[a[i],a[j]]=[a[j],a[i]]}return a}
  function prepareQuestions(id){const src=C.get(id);if(!src)return[];const pool=src.questions||[];const key=`zivo_seen_${id}_v8`;let seen=[];try{seen=JSON.parse(localStorage.getItem(key)||'[]')}catch(e){}let fresh=pool.filter(q=>!seen.includes(q.id));if(fresh.length<10){seen=[];fresh=pool.slice()}const byD=d=>fresh.filter(q=>q.d===d);let chosen=[];for(let d=1;d<=10;d++){const same=byD(d);if(same.length)chosen.push(same[Math.floor(Math.random()*same.length)])}if(chosen.length<10){chosen=[...shuffle(fresh).slice(0,10)];chosen.sort((a,b)=>a.d-b.d)}try{localStorage.setItem(key,JSON.stringify([...seen,...chosen.map(q=>q.id)].slice(-Math.max(30,pool.length))))}catch(e){}return chosen}
  function guestGate(id){openModal(`<button class="modal-close" data-close>×</button><span class="eyebrow">${t('guestMode')}</span><h2>${t('guest')}</h2><p>${t('guestText')}</p><div class="modal-actions"><button class="btn btn-primary" id="continue-guest">${t('continueGuest')}</button><button class="btn btn-ghost" id="create-now">${t('createNow')}</button></div>`);$('#continue-guest').onclick=()=>{closeModal();beginGame(id,true)};$('#create-now').onclick=()=>authModal(()=>beginGame(id,false))}
  function startGame(id){const src=C.get(id);if(!src){toast(t('noData'),'error');return}if(id==='horror'){openModal(`<div class="horror-warning-card"><span class="eyebrow">${t('horrorWarningTitle')}</span><h2>${t('horrorWarningHeadline')}</h2><p>${t('horrorWarningText')}</p><p class="horror-warning">${t('horrorWarningNight')}</p><div class="modal-actions"><button class="btn btn-primary" id="enter-horror">${t('horrorEnter')}</button><button class="btn btn-ghost" data-close>${t('close')}</button></div></div>`,'horror-modal phase-1');$('#enter-horror').onclick=()=>{closeModal();beginGame('horror',!A.isLoggedIn())};return}beginGame(id,!A.isLoggedIn())}
  function beginGame(id,guest){const src=C.get(id),horror=id==='horror';game={id,questions:horror?shuffle(src.questions.map(q=>({...q}))):prepareQuestions(id),index:0,score:0,answers:[],guest,locked:false,horrorSignupShown:false,horrorUsed:[]};if(horror)game.horrorUsed=game.questions.map(q=>q.id);document.body.classList.toggle('horror-active',horror);S().unlock?.();S().startChallenge?.(id);renderQuestion()}
  function currentQ(){return game.questions[game.index]}
  function inputMarkup(q){const isNum=q.type==='number';return `<form id="answer-form" class="input-answer-form"><input id="answer-input" ${isNum?'inputmode="numeric" pattern="[0-9.\\-]+"':''} autocomplete="off" placeholder="${esc(isNum?t('enterNumber'):t('writeAnswer'))}" required><button class="btn btn-primary" type="submit">${t('submitAnswer')}</button></form>`}
  function choiceMarkup(q){const labels=['A','B','C','D'];return `<div class="answers">${q.a.map((x,i)=>`<button class="btn btn-ghost answer" data-i="${i}"><span>${labels[i]}</span>${esc(loc(x))}</button>`).join('')}</div>`}
  function renderQuestion(){const src=C.get(game.id);if(game.id==='horror'&&game.index>=game.questions.length){game.horrorUsed=[];game.questions=shuffle(src.questions.map(q=>({...q})));}const q=currentQ();if(!q){finishGame();return}S().question?.(q.d,game.id);if(game.id==='horror'){horrorNarrate();if(game.index===10)S().phase?.(2);if(game.index===20)S().phase?.(3);if(game.index>0&&game.index%5===0)S().horrorPulse?.(Math.min(4,1+Math.floor(game.index/5)));if(game.index===6)S().warden?.()}const phase=game.id==='horror'?` phase-${game.index<10?1:game.index<20?2:3}`:'';const progress=game.id==='horror'?((game.index%10)/10)*100:Math.round(game.index/game.questions.length*100);const body=q.type==='choice'?choiceMarkup(q):inputMarkup(q);const warden=game.id==='horror'&&game.index>=6?`<div class="warden">${t('warden')}</div>`:'';const footer=game.id==='horror'?`<span class="horror-status">${t('horrorQuestion')} ${game.index+1}</span>`:`<span>${game.score} ${t('correct')}</span>`;const horrorPlayer=game.id==='horror'?`<div class="horror-audio-player"><button type="button" id="horror-audio-toggle" class="btn btn-small btn-ghost">🔊 ${t('horrorAudio')}</button><input id="horror-volume" type="range" min="0" max="1" step="0.01" value="${S().volume?.()||.9}" aria-label="${t('horrorVolume')}"></div>`:'';openModal(`<button class="modal-close" data-action="quit-game" aria-label="Close">×</button><div class="game-head"><span class="eyebrow">${esc(loc(src.title))}</span><strong>${game.id==='horror'?game.index+1:`${game.index+1} / ${game.questions.length}`}</strong></div><div class="question-progress"><span style="width:${progress}%"></span></div>${warden}<h2>${esc(loc(q.q))}</h2><div class="difficulty">${t('difficulty')} ${q.d}/10</div>${body}${horrorPlayer}<div class="game-footer">${footer}<button class="btn btn-small btn-ghost" data-action="quit-game">${t('exit')}</button></div>`,game.id==='horror'?`horror-modal${phase}`:'');if(q.type==='choice')$$('.answer').forEach(b=>b.onclick=()=>{S().click?.();answerChoice(Number(b.dataset.i))});else $('#answer-form').onsubmit=e=>{e.preventDefault();S().click?.();answerInput($('#answer-input').value)};$('#modal-root [data-action="quit-game"]').onclick=quitGame;if(game.id==='horror'){$('#horror-audio-toggle')?.addEventListener('click',async()=>{await S().unlock?.();S().toggle?.();$('#horror-audio-toggle').textContent=(S().isEnabled?.()?'🔊 ':'🔇 ')+t('horrorAudio')});$('#horror-volume')?.addEventListener('input',e=>S().setVolume?.(e.target.value));}}
  function normalize(v){return String(v??'').trim().toLowerCase().replace(/\s+/g,'')}
  function checkInput(q,value){if(q.extra?.answer==='*')return true;const answers=Array.isArray(q.extra?.answer)?q.extra.answer:[q.extra?.answer];return answers.some(a=>normalize(a)===normalize(value))}
  function nextQuestion(delay=500){setTimeout(()=>{game.index++;game.locked=false;if(game.id==='horror'&&game.index%10===0){S().checkpoint?.();horrorCheckpoint();return}if(game.id==='horror'&&game.index===15&&!game.horrorSignupShown){game.horrorSignupShown=true;horrorSignupGate();return}renderQuestion()},delay)}
  function answerChoice(i){if(game.locked)return;game.locked=true;const q=currentQ(),ok=i===q.c;game.answers.push({id:q.id,value:i,ok});if(game.id==='horror'){S().horrorAnswer?.(q.d);nextQuestion(620);return}game.score+=ok?1:0;const bs=$$('.answer');bs.forEach((b,n)=>{b.disabled=true;if(n===q.c)b.classList.add('answer-correct');if(n===i&&!ok)b.classList.add('answer-wrong')});S()[ok?'correct':'wrong']?.();nextQuestion(700)}
  function answerInput(value){if(game.locked||!String(value).trim())return;game.locked=true;const q=currentQ(),ok=checkInput(q,value);game.answers.push({id:q.id,value,ok});if(game.id==='horror'){S().horrorAnswer?.(q.d);nextQuestion(620);return}game.score+=ok?1:0;const form=$('#answer-form');form.classList.add(ok?'input-correct':'input-wrong');S()[ok?'correct':'wrong']?.();nextQuestion(700)}
  function horrorSignupGate(){S().whisper?.();openModal(`<div class="horror-checkpoint signup-horror"><span class="eyebrow">${t('horrorThreshold')}</span><h2>${t('horrorSignupTitle')}</h2><p>${t('horrorSignupText')}</p><p class="horror-warning">${t('horrorWarning')}</p><div class="modal-actions"><button class="btn btn-primary" id="horror-signup">${t('createNow')}</button><button class="btn btn-ghost" id="horror-guest">${t('continueGuest')}</button></div></div>`,'horror-modal phase-2');$('#horror-signup').onclick=()=>authModal(()=>{closeModal();game.guest=false;renderQuestion()});$('#horror-guest').onclick=()=>{closeModal();renderQuestion()}}
  const HORROR_LINES={
    ar:['اسمع جيدًا... أنا لا أبحث عن إجابتك فقط. أنا أراقب الطريقة التي تفكر بها.','أنت ما زلت هنا... معظم الناس يبدأون بالنظر خلفهم الآن.','لا تتوقف. السؤال التالي ينتظرك قبل أن يختفي السابق.','أنا لا أراقب الشاشة فقط... أنا أراقب اختياراتك.','إذا سمعت شيئًا بجانبك، لا تلتفت بسرعة. أكمل.','الوقت هنا لا يشبه الوقت خارج هذه الغرفة.','أنت وصلت إلى مكان يصبح فيه الاستمرار قرارًا.','لا تسأل من أنا. اسأل نفسك لماذا ما زلت تجيب.','لا توجد إجابة تخبرك أنك بأمان. هناك سؤال آخر فقط.','اقتربت... لكن هل اقتربت أنت مني أم أنا منك؟'],
    en:['Listen carefully. I am not only looking for your answer. I am watching how you think.','You are still here... most people start looking behind them by now.','Do not stop. The next question is waiting before the last one disappears.','I am not only watching the screen. I am watching your choices.','If you hear something beside you, do not turn too quickly. Keep answering.','Time here does not behave like time outside this room.','You have reached a place where continuing becomes a decision.','Do not ask who I am. Ask yourself why you are still answering.','There is no answer that tells you that you are safe. Only another question.','You are getting closer... but are you approaching me, or am I approaching you?']
  };
  function horrorNarrate(){
    if(game.id!=='horror')return;
    const lines=HORROR_LINES[lang()]||HORROR_LINES.en;
    const text=lines[Math.min(lines.length-1,Math.floor(game.index/2))];
    if(text)S().narrate?.(text);
  }
  function horrorCheckpoint(){openModal(`<div class="horror-checkpoint"><span class="eyebrow">${t('horrorCheckpoint')}</span><h2>${t('horrorCheckpointTitle')}</h2><p>${t('horrorCheckpointText')}</p><p class="horror-warning">${t('horrorWarning')}</p><div class="modal-actions"><button class="btn btn-primary" id="horror-continue">${t('horrorContinue')}</button><button class="btn btn-ghost" id="horror-exit">${t('horrorLeave')}</button></div></div>`,'horror-modal phase-3');$('#horror-continue').onclick=()=>{closeModal();renderQuestion()};$('#horror-exit').onclick=()=>{closeModal();quitGame()}}
  async function quitGame(){const wasHorror=game.id==='horror';const survived=game.index;S().stopChallenge?.();document.body.classList.remove('horror-active');if(wasHorror){const xp=Math.max(5,survived*7);await reward(xp,Math.max(1,Math.floor(survived/4)),survived>=10);await A.saveResult({challengeId:'horror',score:survived,total:survived,questionsSurvived:survived,endedByPlayer:true,guest:game.guest,xp,language:lang()});openModal(`<button class="modal-close" data-close>×</button><span class="eyebrow">${t('horrorExitTitle')}</span><h2>${t('horrorExitHeadline')}</h2><p>${t('horrorExitText')}</p><p><strong>${survived}</strong> ${t('horrorQuestion')}</p><div class="modal-actions"><button class="btn btn-primary" id="horror-again">${t('again')}</button>${game.guest?`<button class="btn btn-ghost" id="register-result">${t('saveProgress')}</button>`:''}<button class="btn btn-ghost" id="horror-center">${t('backToChallenges')}</button><button class="btn btn-ghost" data-close>${t('close')}</button></div>`);$('#horror-again').onclick=()=>{closeModal();startGame('horror')};$('#horror-center')?.addEventListener('click',exitToChallengeCenter);$('#register-result')?.addEventListener('click',()=>authModal(()=>{toast(t('success'),'success');profile()}));return}closeModal()}
  async function finishGame(){S().stopChallenge?.();document.body.classList.remove('horror-active');S().success?.();const src=C.get(game.id),score=game.score,total=game.questions.length,xp=Math.max(10,Math.round(score/total*src.xp)),coins=Math.max(1,Math.ceil(score/2)),win=score>=Math.ceil(total*.5);await reward(xp,coins,win);if(game.id==='daily')localStorage.setItem('zivo_daily_'+new Date().toISOString().slice(0,10),'1');await A.saveResult({challengeId:game.id,score,total,xp,coins,guest:game.guest,language:lang()});openModal(`<button class="modal-close" data-close>×</button><span class="eyebrow">${t('result')}</span><h2>${win?t('excellent'):t('roundEnded')}</h2><p>${t('score')}: <strong>${score}/${total}</strong></p><p>+${xp} XP &nbsp; +${coins} 🪙 ZIVO</p>${game.guest?`<div class="save-call"><strong>${t('guestSave')}</strong></div>`:''}<div class="modal-actions"><button class="btn btn-primary" id="again">${t('again')}</button>${game.guest?`<button class="btn btn-ghost" id="register-result">${t('saveProgress')}</button>`:''}<button class="btn btn-ghost" id="result-center">${t('backToChallenges')}</button><button class="btn btn-ghost" data-close>${t('close')}</button></div>`);$('#again').onclick=()=>{closeModal();startGame(game.id)};$('#result-center')?.addEventListener('click',exitToChallengeCenter);$('#register-result')?.addEventListener('click',()=>authModal(()=>{toast(t('success'),'success');profile()}))}
  function identity(){const qs=[{q:O('عندما تواجه مشكلة جديدة؟','When facing a new problem?'),a:[O('أحللها بهدوء','Analyze calmly'),O('أجرب بسرعة','Try quickly'),O('أسأل الآخرين','Ask others')]},{q:O('في المنافسة يهمك أكثر؟','In competition, what matters most?'),a:[O('الدقة','Accuracy'),O('السرعة','Speed'),O('الإبداع','Creativity')]},{q:O('عندما تتغير الخطة؟','When the plan changes?'),a:[O('أعيد التخطيط','Re-plan'),O('أتكيف فورًا','Adapt immediately'),O('أبحث عن بديل','Find an alternative')]},{q:O('تفضل؟','You prefer?'),a:[O('التحديات المنطقية','Logic challenges'),O('المغامرة','Adventure'),O('التعاون','Teamwork')]}];let i=0,s=[0,0,0];const step=()=>{if(i>=qs.length){const m=s.indexOf(Math.max(...s)),names=[t('analysis'),t('adventurer'),t('teamPlayer')];state.identity=names[m];saveState();openModal(`<button class="modal-close" data-close>×</button><span class="eyebrow">${t('whoAmI')}</span><h2>${names[m]}</h2><p>${t('identityResult')}</p><button class="btn btn-primary full" data-close>${t('close')}</button>`);return}const q=qs[i];openModal(`<button class="modal-close" data-close>×</button><span class="eyebrow">${t('whoAmI')}</span><h2>${esc(loc(q.q))}</h2><div class="answers">${q.a.map((x,n)=>`<button class="btn btn-ghost id-choice" data-n="${n}">${esc(loc(x))}</button>`).join('')}</div>`);$$('.id-choice').forEach(b=>b.onclick=()=>{s[Number(b.dataset.n)]++;i++;step()})};step()}
  function renderChallenges(){const today=new Date().toISOString().slice(0,10),done=localStorage.getItem('zivo_daily_'+today);const raw=C.getAll();const seenIds=new Set();const list=raw.filter(x=>x&&x.id&&!seenIds.has(x.id)&&seenIds.add(x.id));$('#challenge-list').innerHTML=list.map(x=>`<article class="challenge-card"><span class="challenge-icon">${x.icon}</span><div><span class="card-tag">${t('questions10')}</span><h3>${esc(loc(x.title))}</h3><p>${esc(loc(x.desc))}</p></div><button class="btn btn-primary" data-challenge="${x.id}" ${done&&x.id==='daily'?'disabled':''}>${done&&x.id==='daily'?t('done'):t('start')}</button></article>`).join('')+`<article class="challenge-card special"><span class="challenge-icon">👁️</span><div><span class="card-tag danger">∞</span><h3>${esc(loc(C.horror.title))}</h3><p>${esc(loc(C.horror.desc))}</p></div><button class="btn btn-primary danger-btn" data-challenge="horror">${t('enter')}</button></article>`}
  const NEWS=[{key:'FIFA',url:'https://www.fifa.com/',icon:'🌍',title:O('فيفا','FIFA')},{key:'AFC',url:'https://www.the-afc.com/',icon:'🏆',title:O('الاتحاد الآسيوي','AFC')},{key:'UEFA',url:'https://www.uefa.com/',icon:'⭐',title:O('يويفا','UEFA')},{key:'ESPN',url:'https://www.espn.com/',icon:'📰',title:O('ESPN','ESPN')}];
  function renderNewsSources(){const box=$('#news-list');if(!box)return;box.innerHTML=NEWS.map(n=>`<article class="sports-card"><div class="icon">${n.icon}</div><span class="card-tag">${n.key}</span><h3>${esc(loc(n.title))}</h3><p>${esc(t('sportsIntro'))}</p><a class="btn btn-ghost" href="${n.url}" target="_blank" rel="noopener noreferrer">${t('openNews')}</a></article>`).join('')}
  async function sports(){renderNewsSources();window.ZIVOZONE_NEWS?.load?.($('#news-list'),lang());window.ZIVOZONE_NEWS?.loadJordan?.($('#jordan-news-list'),lang());const box=$('#sports-list');if(!box)return;box.innerHTML=`<article class="sports-card loading-card"><div class="spinner"></div><h3>${esc(t('sportsTitle'))}</h3><p>${esc(t('loader'))}</p></article>`;const teamIds=['133604','133602','133738','133739'];let events=[];try{const data=await Promise.all(teamIds.map(id=>fetch(`https://www.thesportsdb.com/api/v1/json/123/eventsnext.php?id=${id}`).then(r=>r.ok?r.json():null).catch(()=>null)));data.forEach(d=>{if(d?.events)events.push(...d.events)})}catch(e){}const seen=new Set();events=events.filter(e=>{const k=e.idEvent||`${e.strEvent}-${e.dateEvent}`;if(seen.has(k))return false;seen.add(k);return true}).slice(0,8);if(!events.length){box.innerHTML=`<article class="sports-card"><div class="icon">📡</div><h3>${esc(t('noData'))}</h3><p>${esc(t('newsUnavailable'))}</p></article>`;return}box.innerHTML=events.map(e=>`<article class="sports-card"><div class="match-icon">⚽</div><span class="card-tag">${esc(e.strLeague||e.strSport||'Sport')}</span><h3>${esc(e.strHomeTeam||'Home')} <span class="versus">VS</span> ${esc(e.strAwayTeam||'Away')}</h3><p>${esc(e.dateEvent||'')} ${esc(e.strTime||'')}</p><a class="btn btn-ghost" href="https://www.thesportsdb.com/" target="_blank" rel="noopener noreferrer">${t('open')}</a></article>`).join('')}
  function localAIReply(q){const x=q.toLowerCase();if(x.includes('مستوى')||x.includes('level')||x.includes('等级')||x.includes('nivel'))return`${t('level')} ${state.level} — ${state.xp} XP, ${state.coins} ZIVO.`;if(x.includes('تحد')||x.includes('challenge')||x.includes('挑战')||x.includes('desaf'))return t('challengeText');if(x.includes('رياض')||x.includes('sport')||x.includes('体育')||x.includes('deporte'))return t('sportsIntro');return t('aiWelcome')}
  async function askAI(message){if(API.aiEndpoint){try{const r=await fetch(API.aiEndpoint,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({message,language:lang(),player:{level:state.level,xp:state.xp,gamesPlayed:state.gamesPlayed}})});if(r.ok){const d=await r.json();if(d.reply)return d.reply}}catch(e){}}return localAIReply(message)}
  function applyLanguage(){const l=lang();document.documentElement.lang=l;document.documentElement.dir=I.dir[l];$$('[data-i18n]').forEach(el=>{const k=el.dataset.i18n;if(I.T[l]?.[k]!==undefined)el.textContent=t(k)});$$('[data-i18n-placeholder]').forEach(el=>el.placeholder=t(el.dataset.i18nPlaceholder));renderChallenges();renderNewsSources();profile();sports();$('#footer-tagline')?.replaceChildren(document.createTextNode(t('footerTagline')))}
  document.addEventListener('click',e=>{const gameBtn=e.target.closest('[data-game],[data-challenge]');if(gameBtn){e.preventDefault();startGame(gameBtn.dataset.game||gameBtn.dataset.challenge);return}const action=e.target.closest('[data-action]')?.dataset.action;if(action==='scroll-games'||action==='scroll-challenges'){e.preventDefault();$('#challenges')?.scrollIntoView({behavior:'smooth'});return}if(action==='open-identity'){identity();return}if(action==='login'){A.isLoggedIn()?location.hash='#profile':authModal();return}if(action==='logout'){A.logout().then(()=>{state={level:1,xp:0,coins:0,wins:0,gamesPlayed:0,identity:null};saveState();profile();toast(t('logoutDone'))});return}if(action==='refresh-sports'){sports();return}if(action==='ad-info'){toast(t('adText'));return}if(action==='ads-control'){window.ZIVOZONE_ADS?.open?.();return}});
  function bind(){const audioBtn=$('#audio-toggle');if(audioBtn){audioBtn.textContent=S().isEnabled?.()?'🔊':'🔇';audioBtn.onclick=async()=>{await S().unlock?.();S().toggle?.();audioBtn.textContent=S().isEnabled?.()?'🔊':'🔇'}}$('#language-select').value=lang();$('#language-select').onchange=async e=>{I.set(e.target.value);await A.setLanguage(e.target.value);applyLanguage();toast(t('updateDone'),'success')};$('#login-btn').onclick=()=>A.isLoggedIn()?location.hash='#profile':authModal();$$('[data-action="login"]').forEach(b=>b.onclick=()=>A.isLoggedIn()?location.hash='#profile':authModal());$('#ai-form').onsubmit=async e=>{e.preventDefault();const input=$('#ai-input'),v=input.value.trim();if(!v)return;const box=$('#ai-messages');const u=document.createElement('div');u.className='ai-message user';u.textContent=v;box.append(u);input.value='';const b=document.createElement('div');b.className='ai-message bot';b.textContent='…';box.append(b);b.textContent=await askAI(v);box.scrollTop=box.scrollHeight}}
  window.addEventListener('zivozone-auth',e=>{syncFromPlayer();profile();const el=$('#firebase-status');if(el){el.textContent=e.detail?.cloud?'●':'○';el.classList.toggle('online',!!e.detail?.cloud);el.title=e.detail?.cloud?'Firebase connected':'Guest/local mode'}});
  window.addEventListener('zivozone-language',()=>{const sel=$('#language-select');if(sel)sel.value=lang()});
  loadState();document.addEventListener('DOMContentLoaded',()=>{bind();applyLanguage();setTimeout(()=>$('#app-loader')?.classList.add('hidden'),650)});
})();
