/* ============================================================
   ZIVOZONE EXPANSION BANK v6
   Adds 5 complete challenge worlds. Existing banks are preserved.
   12 questions per new challenge, difficulty 1-10.
============================================================ */
(() => {
  'use strict';
  const C=window.ZIVOZONE_CHALLENGES;
  if(!C) return;
  const L=(ar,en,zh,hi,es)=>({ar,en,zh,hi,es});
  const O=(ar,en,zh,hi,es)=>L(ar,en,zh,hi,es);
  const E=(q,a,c,d)=>({q,a,c,d});
  const add=(id,icon,xp,title,desc,questions)=>{C[id]={id,icon,xp,title:L(...title),desc:L(...desc),questions};questions.forEach((q,i)=>q.id=q.id||`${id}_${i+1}`)};

  add('math','➗',85,
    ['تحدي الرياضيات','Math Master Challenge','数学大师挑战','मैथ मास्टर चैलेंज','Desafío Maestro de Matemáticas'],
    ['12 مسألة من الحساب السريع إلى المنطق الرياضي.','12 problems from quick arithmetic to mathematical reasoning.','12道题，从快速计算到数学推理。','12 सवाल, तेज़ गणना से गणितीय तर्क तक।','12 problemas, del cálculo rápido al razonamiento matemático.'],[
      E(L('18 + 27 = ؟','18 + 27 = ?','18 + 27 = ?','18 + 27 = ?','18 + 27 = ?'),[O('35','35','35','35','35'),O('45','45','45','45','45'),O('55','55','55','55','55'),O('65','65','65','65','65')],1,1),
      E(L('9 × 7 = ؟','9 × 7 = ?','9 × 7 = ?','9 × 7 = ?','9 × 7 = ?'),[O('54','54','54','54','54'),O('63','63','63','63','63'),O('72','72','72','72','72'),O('81','81','81','81','81')],1,1),
      E(L('ما قيمة 3² + 4²؟','What is 3² + 4²?','3² + 4² 等于多少？','3² + 4² कितना है?','¿Cuánto es 3² + 4²?'),[O('12','12','12','12','12'),O('20','20','20','20','20'),O('25','25','25','25','25'),O('49','49','49','49','49')],2,2),
      E(L('إذا كان x + 8 = 21، فما قيمة x؟','If x + 8 = 21, what is x?','如果 x + 8 = 21，x 是多少？','यदि x + 8 = 21, तो x कितना है?','Si x + 8 = 21, ¿cuánto vale x?'),[O('11','11','11','11','11'),O('12','12','12','12','12'),O('13','13','13','13','13'),O('14','14','14','14','14')],2,2),
      E(L('ما العدد التالي: 5، 10، 20، 40، ؟','What comes next: 5, 10, 20, 40, ?','下一个数字：5、10、20、40、？','अगली संख्या: 5, 10, 20, 40, ?','¿Qué sigue: 5, 10, 20, 40, ?'),[O('60','60','60','60','60'),O('70','70','70','70','70'),O('80','80','80','80','80'),O('90','90','90','90','90')],2,4),
      E(L('ما متوسط 10 و20 و30؟','What is the average of 10, 20 and 30?','10、20、30的平均数是多少？','10, 20 और 30 का औसत क्या है?','¿Cuál es el promedio de 10, 20 y 30?'),[O('15','15','15','15','15'),O('20','20','20','20','20'),O('25','25','25','25','25'),O('30','30','30','30','30')],1,5),
      E(L('إذا كان 4 عمال ينجزون مهمة في 6 أيام، فكم عاملًا يحتاجون نظريًا لإنجازها في 3 أيام بنفس الكفاءة؟','If 4 workers finish a task in 6 days, how many workers are theoretically needed in 3 days at the same rate?','4名工人6天完成任务，同样效率下3天需要多少人？','4 मजदूर 6 दिन में काम करते हैं। समान गति पर 3 दिन में कितने मजदूर चाहिए?','Si 4 trabajadores terminan una tarea en 6 días, ¿cuántos se necesitan en 3 días al mismo ritmo?'),[O('6','6','6','6','6'),O('8','8','8','8','8'),O('10','10','10','10','10'),O('12','12','12','12','12')],1,6),
      E(L('ما قيمة 2³ × 2²؟','What is 2³ × 2²?','2³ × 2² 等于多少？','2³ × 2² कितना है?','¿Cuánto es 2³ × 2²?'),[O('16','16','16','16','16'),O('24','24','24','24','24'),O('32','32','32','32','32'),O('64','64','64','64','64')],2,7),
      E(L('إذا كان محيط مربع 36 سم، فما طول ضلعه؟','A square has perimeter 36 cm. What is its side length?','正方形周长36厘米，边长是多少？','एक वर्ग का परिमाप 36 सेमी है। भुजा कितनी है?','Un cuadrado tiene un perímetro de 36 cm. ¿Cuál es su lado?'),[O('6','6','6','6','6'),O('8','8','8','8','8'),O('9','9','9','9','9'),O('12','12','12','12','12')],2,8),
      E(L('إذا كان احتمال حدث 1/4، فما النسبة المئوية؟','If an event has probability 1/4, what percentage is that?','事件概率为1/4，对应百分比是多少？','यदि किसी घटना की प्रायिकता 1/4 है, तो प्रतिशत कितना है?','Si la probabilidad de un evento es 1/4, ¿qué porcentaje es?'),[O('20%','20%','20%','20%','20%'),O('25%','25%','25%','25%','25%'),O('40%','40%','40%','40%','40%'),O('50%','50%','50%','50%','50%')],1,9),
      E(L('عدد موجب إذا ضربته في نفسه ثم أضفت 5 حصلت على 30. ما العدد؟','A positive number squared plus 5 equals 30. What is the number?','一个正数的平方加5等于30。这个数是多少？','एक धनात्मक संख्या का वर्ग + 5 = 30। संख्या क्या है?','El cuadrado de un número positivo más 5 es 30. ¿Cuál es?'),[O('4','4','4','4','4'),O('5','5','5','5','5'),O('6','6','6','6','6'),O('7','7','7','7','7')],1,10),
      E(L('إذا كان مجموع ثلاثة أعداد متتالية هو 72، فما العدد الأوسط؟','Three consecutive integers sum to 72. What is the middle integer?','三个连续整数之和为72，中间的整数是多少？','तीन क्रमागत पूर्णांकों का योग 72 है। बीच की संख्या क्या है?','Tres enteros consecutivos suman 72. ¿Cuál es el del medio?'),[O('23','23','23','23','23'),O('24','24','24','24','24'),O('25','25','25','25','25'),O('26','26','26','26','26')],1,10)
    ]);

  add('memory','🧩',75,
    ['تحدي الذاكرة','Memory Challenge','记忆挑战','मेमोरी चैलेंज','Desafío de Memoria'],
    ['اختبر تذكرك وتسلسل المعلومات تحت الضغط.','Test recall and sequence memory under pressure.','在压力下测试记忆和顺序能力。','दबाव में याददाश्त और क्रम की परीक्षा।','Pon a prueba la memoria y el orden bajo presión.'],[
      E(L('تذكّر: أحمر، أزرق، أخضر. ما اللون الثاني؟','Remember: Red, Blue, Green. What was the second color?','记住：红、蓝、绿。第二个颜色是什么？','याद रखें: लाल, नीला, हरा। दूसरा रंग कौन सा था?','Recuerda: rojo, azul, verde. ¿Cuál era el segundo color?'),[O('أحمر','Red','红','लाल','Rojo'),O('أزرق','Blue','蓝','नीला','Azul'),O('أخضر','Green','绿','हरा','Verde'),O('أصفر','Yellow','黄','पीला','Amarillo')],1,1),
      E(L('تذكّر الأرقام: 4، 9، 2، 7. ما الرقم الأخير؟','Remember: 4, 9, 2, 7. What was the last number?','记住：4、9、2、7。最后一个数字是什么？','याद रखें: 4, 9, 2, 7. आखिरी संख्या क्या थी?','Recuerda: 4, 9, 2, 7. ¿Cuál era el último número?'),[O('2','2','2','2','2'),O('4','4','4','4','4'),O('7','7','7','7','7'),O('9','9','9','9','9')],2,1),
      E(L('أي كلمة ظهرت أولًا: قمر، باب، نهر؟','Which word appeared first: Moon, Door, River?','哪个词最先出现：月亮、门、河？','कौन सा शब्द पहले आया: चाँद, दरवाज़ा, नदी?','¿Qué palabra apareció primero: Luna, Puerta, Río?'),[O('نهر','River','河','नदी','Río'),O('قمر','Moon','月亮','चाँद','Luna'),O('باب','Door','门','दरवाज़ा','Puerta'),O('لا أتذكر','I do not remember','不记得','मुझे याद नहीं','No recuerdo')],1,2),
      E(L('السلسلة: 8، 3، 6، 1. ما الرقم الثالث؟','Sequence: 8, 3, 6, 1. What was the third number?','序列：8、3、6、1。第三个数字是什么？','क्रम: 8, 3, 6, 1. तीसरी संख्या क्या थी?','Secuencia: 8, 3, 6, 1. ¿Cuál era el tercero?'),[O('1','1','1','1','1'),O('3','3','3','3','3'),O('6','6','6','6','6'),O('8','8','8','8','8')],2,3),
      E(L('تذكّر: كرة، كتاب، مفتاح، شجرة. ما الشيء الذي يمكن فتحه؟','Remember: Ball, Book, Key, Tree. Which item can open something?','记住：球、书、钥匙、树。哪个东西可以打开东西？','याद रखें: गेंद, किताब, चाबी, पेड़। कौन सी चीज़ कुछ खोल सकती है?','Recuerda: pelota, libro, llave, árbol. ¿Qué puede abrir algo?'),[O('كرة','Ball','球','गेंद','Pelota'),O('كتاب','Book','书','किताब','Libro'),O('مفتاح','Key','钥匙','चाबी','Llave'),O('شجرة','Tree','树','पेड़','Árbol')],2,4),
      E(L('إذا عُرضت لك أربعة رموز ثم اختفى واحد، ما أفضل استراتيجية؟','If four symbols are shown and one disappears, what is the best strategy?','显示四个符号后一个消失，最佳策略是什么？','चार प्रतीक दिखाकर एक गायब हो जाए तो सबसे अच्छी रणनीति क्या है?','Si ves cuatro símbolos y uno desaparece, ¿cuál es la mejor estrategia?'),[O('التخمين العشوائي','Random guessing','随机猜测','यादृच्छिक अनुमान','Adivinar al azar'),O('تكرار العناصر ذهنيًا','Mentally rehearse the items','在脑中重复元素','मन में तत्व दोहराना','Repetir mentalmente los elementos'),O('إغلاق اللعبة','Close the game','关闭游戏','खेल बंद करना','Cerrar el juego'),O('تجاهلها','Ignore it','忽略它','इसे अनदेखा करना','Ignorarlo')],1,5),
      E(L('أي ترتيب أسهل للحفظ عادةً؟','Which sequence is usually easier to remember?','哪种顺序通常更容易记住？','कौन सा क्रम आमतौर पर याद रखना आसान है?','¿Qué secuencia suele ser más fácil de recordar?'),[O('معلومات عشوائية بلا نمط','Random information without a pattern','无规律的随机信息','बिना पैटर्न की जानकारी','Información aleatoria sin patrón'),O('معلومات منظمة في مجموعات','Information grouped into chunks','分组组织的信息','समूहों में व्यवस्थित जानकारी','Información agrupada'),O('معلومات متداخلة جدًا','Highly mixed information','高度混杂的信息','बहुत मिश्रित जानकारी','Información muy mezclada'),O('معلومات أطول دائمًا','Always longer information','总是更长的信息','हमेशा लंबी जानकारी','Información siempre más larga')],1,6),
      E(L('ما الذي يساعد الذاكرة العاملة أكثر أثناء التحدي؟','What helps working memory most during a challenge?','挑战中什么最有助于工作记忆？','चैलेंज में कार्यशील स्मृति को क्या सबसे अधिक मदद करता है?','¿Qué ayuda más a la memoria de trabajo durante un desafío?'),[O('التجميع والتنظيم','Chunking and organization','分块与组织','समूह बनाना और व्यवस्थित करना','Agrupar y organizar'),O('تشتيت الانتباه','Distraction','分散注意力','ध्यान भटकाना','Distraerse'),O('تغيير الإجابة عشوائيًا','Randomly changing answers','随机改变答案','उत्तर बेतरतीब बदलना','Cambiar respuestas al azar'),O('تجاهل التسلسل','Ignore sequence','忽略顺序','क्रम को अनदेखा करना','Ignorar el orden')],0,7),
      E(L('إذا تذكرت بداية القائمة ونهايتها، فما الظاهرة الشائعة؟','If you remember the beginning and end of a list better, what is this called?','如果你更容易记住列表的开头和结尾，这种现象叫什么？','यदि सूची की शुरुआत और अंत बेहतर याद रहें, तो इसे क्या कहते हैं?','Si recuerdas mejor el principio y el final de una lista, ¿qué fenómeno es?'),[O('تأثير التسلسل','Serial position effect','系列位置效应','सीरियल पोज़िशन प्रभाव','Efecto de posición serial'),O('تأثير اللون','Color effect','颜色效应','रंग प्रभाव','Efecto de color'),O('تأثير السرعة','Speed effect','速度效应','गति प्रभाव','Efecto de velocidad'),O('لا توجد ظاهرة','No phenomenon','没有现象','कोई प्रभाव नहीं','Ningún fenómeno')],0,8),
      E(L('أثناء الحفظ، أيهما أفضل عادةً: تكرار المعنى أم النظر فقط؟','During memorization, what is usually better: semantic rehearsal or just looking?','记忆时，通常哪种更好：理解意义还是只看？','याद करते समय अर्थपूर्ण दोहराव या केवल देखना बेहतर है?','Al memorizar, ¿qué suele ser mejor: repetir con significado o solo mirar?'),[O('النظر فقط','Just looking','只看','केवल देखना','Solo mirar'),O('ربط المعنى بالمعلومة','Linking meaning to the information','把意义与信息联系起来','अर्थ को जानकारी से जोड़ना','Relacionar el significado con la información'),O('إغلاق العينين فورًا','Close eyes immediately','立即闭眼','तुरंत आँखें बंद करना','Cerrar los ojos de inmediato'),O('التخمين','Guessing','猜测','अनुमान','Adivinar')],1,9),
      E(L('في اختبار ذاكرة سريع، ما الاستراتيجية الأقوى عند ظهور سلسلة طويلة؟','In a rapid memory test, what is a strong strategy for a long sequence?','在快速记忆测试中，面对长序列的强策略是什么？','तेज़ मेमोरी टेस्ट में लंबी श्रृंखला के लिए मजबूत रणनीति क्या है?','En una prueba rápida de memoria, ¿qué estrategia es fuerte para una secuencia larga?'),[O('تقسيمها إلى وحدات ذات معنى','Break it into meaningful chunks','分成有意义的组块','अर्थपूर्ण समूहों में बाँटना','Dividirla en bloques con significado'),O('حفظ آخر عنصر فقط','Remember only the last item','只记最后一个','केवल आखिरी तत्व याद रखना','Recordar solo el último'),O('تجاهل النمط','Ignore the pattern','忽略模式','पैटर्न को अनदेखा करना','Ignorar el patrón'),O('تغيير الترتيب','Change the order','改变顺序','क्रम बदलना','Cambiar el orden')],0,10)
    ]);

  add('geography','🌍',70,
    ['تحدي الجغرافيا','Geography Challenge','地理挑战','जियोग्राफी चैलेंज','Desafío de Geografía'],
    ['12 سؤالًا عن العالم والخرائط والمواقع.','12 questions about the world, maps and locations.','12道关于世界、地图和地点的问题。','दुनिया, नक्शों और स्थानों पर 12 सवाल।','12 preguntas sobre el mundo, mapas y lugares.'],[
      E(L('ما أكبر قارة من حيث المساحة؟','Which is the largest continent by area?','按面积哪个洲最大？','क्षेत्रफल के अनुसार सबसे बड़ा महाद्वीप कौन सा है?','¿Cuál es el continente más grande por superficie?'),[O('أفريقيا','Africa','非洲','अफ्रीका','África'),O('آسيا','Asia','亚洲','एशिया','Asia'),O('أوروبا','Europe','欧洲','यूरोप','Europa'),O('أمريكا الجنوبية','South America','南美洲','दक्षिण अमेरिका','Sudamérica')],1,1),
      E(L('ما عاصمة اليابان؟','What is the capital of Japan?','日本首都是什么？','जापान की राजधानी क्या है?','¿Cuál es la capital de Japón?'),[O('سيول','Seoul','首尔','सियोल','Seúl'),O('بكين','Beijing','北京','बीजिंग','Pekín'),O('طوكيو','Tokyo','东京','टोक्यो','Tokio'),O('أوساكا','Osaka','大阪','ओसाका','Osaka')],2,1),
      E(L('أي محيط يقع بين أفريقيا وأستراليا؟','Which ocean lies between Africa and Australia?','非洲和澳大利亚之间是哪片海洋？','अफ्रीका और ऑस्ट्रेलिया के बीच कौन सा महासागर है?','¿Qué océano está entre África y Australia?'),[O('الأطلسي','Atlantic','大西洋','अटलांटिक','Atlántico'),O('الهندي','Indian','印度洋','हिंद महासागर','Índico'),O('الهادئ','Pacific','太平洋','प्रशांत','Pacífico'),O('المتجمد الشمالي','Arctic','北冰洋','आर्कटिक','Ártico')],1,2),
      E(L('في أي قارة تقع البرازيل؟','Which continent is Brazil in?','巴西位于哪个洲？','ब्राज़ील किस महाद्वीप में है?','¿En qué continente está Brasil?'),[O('آسيا','Asia','亚洲','एशिया','Asia'),O('أفريقيا','Africa','非洲','अफ्रीका','África'),O('أمريكا الجنوبية','South America','南美洲','दक्षिण अमेरिका','Sudamérica'),O('أوروبا','Europe','欧洲','यूरोप','Europa')],2,2),
      E(L('ما السلسلة الجبلية التي تمتد على غرب أمريكا الجنوبية؟','Which mountain range runs along western South America?','哪条山脉沿南美洲西部延伸？','दक्षिण अमेरिका के पश्चिम में कौन सी पर्वत श्रृंखला है?','¿Qué cordillera recorre el oeste de Sudamérica?'),[O('الألب','Alps','阿尔卑斯山','आल्प्स','Alpes'),O('الأنديز','Andes','安第斯山脉','एंडीज','Andes'),O('الهيمالايا','Himalayas','喜马拉雅山','हिमालय','Himalaya'),O('الروكي','Rockies','落基山脉','रॉकी','Rocosas')],1,4),
      E(L('أي دولة تشتهر بوجود مدينة سيدني؟','Which country is known for the city of Sydney?','悉尼位于哪个国家？','सिडनी किस देश में है?','¿En qué país está Sídney?'),[O('كندا','Canada','加拿大','कनाडा','Canadá'),O('أستراليا','Australia','澳大利亚','ऑस्ट्रेलिया','Australia'),O('نيوزيلندا','New Zealand','新西兰','न्यूज़ीलैंड','Nueva Zelanda'),O('جنوب أفريقيا','South Africa','南非','दक्षिण अफ्रीका','Sudáfrica')],1,4),
      E(L('ما الخط الوهمي الذي يقسم الأرض إلى نصفين شمالي وجنوبي؟','Which imaginary line divides Earth into northern and southern hemispheres?','哪条假想线把地球分成南北半球？','कौन सी काल्पनिक रेखा पृथ्वी को उत्तरी और दक्षिणी गोलार्ध में बाँटती है?','¿Qué línea imaginaria divide la Tierra en hemisferios norte y sur?'),[O('خط الاستواء','Equator','赤道','भूमध्य रेखा','Ecuador'),O('خط غرينتش','Prime Meridian','本初子午线','प्रधान मध्याह्न','Meridiano de Greenwich'),O('مدار السرطان','Tropic of Cancer','北回归线','कर्क रेखा','Trópico de Cáncer'),O('مدار الجدي','Tropic of Capricorn','南回归线','मकर रेखा','Trópico de Capricornio')],0,5),
      E(L('أي دولة تقع في شبه الجزيرة العربية وتطل على البحر الأحمر وخليج عدن؟','Which country on the Arabian Peninsula borders the Red Sea and Gulf of Aden?','阿拉伯半岛上哪个国家濒临红海和亚丁湾？','अरब प्रायद्वीप का कौन सा देश लाल सागर और अदन की खाड़ी से जुड़ा है?','¿Qué país de la península arábiga limita con el mar Rojo y el golfo de Adén?'),[O('اليمن','Yemen','也门','यमन','Yemen'),O('العراق','Iraq','伊拉克','इराक','Irak'),O('الأردن','Jordan','约旦','जॉर्डन','Jordania'),O('لبنان','Lebanon','黎巴嫩','लेबनान','Líbano')],0,6),
      E(L('إذا اتجهت شرقًا من خط غرينتش، ماذا يحدث لقيمة خط الطول؟','If you travel east from the Prime Meridian, what happens to longitude?','从本初子午线向东， 经度值如何变化？','प्रधान मध्याह्न से पूर्व की ओर जाने पर देशांतर कैसे बदलता है?','Si viajas al este del meridiano de Greenwich, ¿qué pasa con la longitud?'),[O('تزداد شرقًا','It increases eastward','向东增加','पूर्व की ओर बढ़ता है','Aumenta hacia el este'),O('تختفي','It disappears','消失','गायब हो जाता है','Desaparece'),O('تبقى صفرًا','It stays zero','保持为零','शून्य रहता है','Permanece en cero'),O('تتغير إلى خط عرض','It becomes latitude','变成纬度','अक्षांश बन जाता है','Se convierte en latitud')],0,7),
      E(L('ما الدولة التي يمر بها نهر النيل قبل وصوله إلى البحر المتوسط في شمال أفريقيا؟','Which country does the Nile reach before the Mediterranean in North Africa?','尼罗河在到达地中海前流经北非哪个国家？','नील नदी भूमध्य सागर से पहले उत्तर अफ्रीका के किस देश से गुजरती है?','¿En qué país del norte de África llega el Nilo al Mediterráneo?'),[O('مصر','Egypt','埃及','मिस्र','Egipto'),O('الجزائر','Algeria','阿尔及利亚','अल्जीरिया','Argelia'),O('المغرب','Morocco','摩洛哥','मोरक्को','Marruecos'),O('تونس','Tunisia','突尼斯','ट्यूनीशिया','Túnez')],0,8),
      E(L('إذا كانت الخريطة بمقياس 1:100000، فكل 1 سم يمثل كم على الأرض؟','On a 1:100000 map scale, what does 1 cm represent on the ground?','地图比例尺1:100000时，1厘米代表地面多少？','1:100000 मानचित्र पैमाने पर 1 सेमी जमीन पर कितना दर्शाता है?','En una escala 1:100000, ¿qué representa 1 cm en el terreno?'),[O('100 م','100 m','100米','100 मीटर','100 m'),O('1 كم','1 km','1千米','1 किमी','1 km'),O('10 كم','10 km','10千米','10 किमी','10 km'),O('100 كم','100 km','100千米','100 किमी','100 km')],1,9),
      E(L('ما أفضل أداة لتحديد الموقع بدقة باستخدام الأقمار الصناعية؟','What tool uses satellites to determine location precisely?','哪种工具利用卫星精确确定位置？','उपग्रहों का उपयोग करके सटीक स्थान निर्धारित करने वाला उपकरण कौन सा है?','¿Qué herramienta usa satélites para determinar la ubicación con precisión?'),[O('GPS','GPS','GPS','GPS','GPS'),O('بارومتر','Barometer','气压计','बैरोमीटर','Barómetro'),O('بوصلة فقط','Compass only','仅指南针','केवल कम्पास','Solo brújula'),O('مقياس حرارة','Thermometer','温度计','थर्मामीटर','Termómetro')],0,10)
    ]);

  add('strategy','♟️',95,
    ['تحدي الاستراتيجية','Strategy Challenge','策略挑战','स्ट्रैटेजी चैलेंज','Desafío de Estrategia'],
    ['قرارات تحت الضغط: اختر الحل الأقوى لا الأسرع.','Decision-making under pressure: choose the strongest solution, not merely the fastest.','压力下决策：选择更强的方案，而不只是更快的。','दबाव में निर्णय: सिर्फ तेज़ नहीं, सबसे मजबूत समाधान चुनें।','Decisiones bajo presión: elige la mejor solución, no solo la más rápida.'],[
      E(L('خصمك أقوى منك مباشرة. ما أول خطوة منطقية؟','Your opponent is directly stronger than you. What is a logical first step?','对手正面实力更强。第一步应是什么？','प्रतिद्वंद्वी सीधे तौर पर मजबूत है। पहला तार्किक कदम क्या है?','Tu rival es directamente más fuerte. ¿Cuál es un primer paso lógico?'),[O('مواجهته بلا خطة','Face them without a plan','无计划正面对抗','बिना योजना सामना करना','Enfrentarlo sin plan'),O('تغيير ظروف المواجهة لصالحك','Change the conditions in your favor','改变条件以利于自己','परिस्थितियों को अपने पक्ष में बदलना','Cambiar las condiciones a tu favor'),O('الاستسلام','Give up','放弃','हार मानना','Rendirse'),O('تجاهله','Ignore them','忽略对手','उसे अनदेखा करना','Ignorarlo')],1,1),
      E(L('لديك وقت محدود ومعلومتان غير مؤكّدتين. ماذا تفعل؟','You have limited time and two uncertain pieces of information. What do you do?','时间有限且有两条不确定信息，你怎么办？','समय सीमित है और दो अनिश्चित जानकारी हैं। क्या करेंगे?','Tienes poco tiempo y dos datos inciertos. ¿Qué haces?'),[O('أفترض أنهما صحيحان','Assume both are true','假设都是真的','दोनों को सही मानना','Suponer que ambas son ciertas'),O('أحدد ما يمكن التحقق منه أولًا','Verify what matters first','先验证关键内容','पहले महत्वपूर्ण चीज़ की पुष्टि करना','Verificar primero lo importante'),O('أختار عشوائيًا','Choose randomly','随机选择','यादृच्छिक चुनना','Elegir al azar'),O('أتوقف دائمًا','Always stop','总是停止','हमेशा रुकना','Detenerse siempre')],1,3),
      E(L('إذا كانت مكافأة القرار عالية لكن احتمال نجاحه منخفض جدًا، ما المفهوم الذي يجب حسابه؟','If a decision has a high reward but very low success probability, what concept should you consider?','如果决策回报高但成功概率很低，应考虑什么概念？','यदि इनाम बहुत बड़ा लेकिन सफलता की संभावना बहुत कम है, तो किस अवधारणा पर विचार करना चाहिए?','Si una decisión tiene gran recompensa pero muy baja probabilidad de éxito, ¿qué concepto debes considerar?'),[O('القيمة المتوقعة','Expected value','期望值','अपेक्षित मूल्य','Valor esperado'),O('اللون','Color','颜色','रंग','Color'),O('السرعة فقط','Speed only','只看速度','केवल गति','Solo velocidad'),O('الحظ فقط','Luck only','只看运气','केवल भाग्य','Solo suerte')],0,5),
      E(L('في لعبة فريق، ما الذي يقلل الفوضى أكثر؟','In a team game, what reduces chaos most?','团队游戏中什么最能减少混乱？','टीम गेम में अराजकता सबसे अधिक किससे घटती है?','En un juego de equipo, ¿qué reduce más el caos?'),[O('أدوار واضحة','Clear roles','明确角色','स्पष्ट भूमिकाएँ','Roles claros'),O('أن يتخذ الجميع نفس القرار','Everyone makes the same decision','所有人做同一决定','सभी एक ही निर्णय लें','Que todos tomen la misma decisión'),O('الصمت الكامل','Complete silence','完全沉默','पूर्ण मौन','Silencio total'),O('التصرف الفردي دائمًا','Always acting alone','总是单独行动','हमेशा अकेले काम करना','Actuar siempre solo')],0,5),
      E(L('عندما تفشل الخطة الأولى، ما السلوك الاستراتيجي الأفضل؟','When the first plan fails, what is the best strategic behavior?','第一方案失败时，最佳战略行为是什么？','पहली योजना विफल होने पर सर्वोत्तम रणनीतिक व्यवहार क्या है?','Cuando falla el primer plan, ¿cuál es el mejor comportamiento estratégico?'),[O('تكرارها بلا تغيير','Repeat it unchanged','不改变地重复','बिना बदलाव दोहराना','Repetirla sin cambios'),O('تحليل سبب الفشل وتعديل الخطة','Analyze the failure and adapt the plan','分析失败并调整计划','विफलता का विश्लेषण और योजना बदलना','Analizar el fallo y adaptar el plan'),O('لوم الفريق فقط','Only blame the team','只责怪团队','केवल टीम को दोष देना','Culpar al equipo'),O('التوقف عن التفكير','Stop thinking','停止思考','सोचना बंद करना','Dejar de pensar')],1,6),
      E(L('خصمك يتوقع قرارك المعتاد. ما أفضل طريقة لاستغلال ذلك؟','Your opponent expects your usual decision. What is a good way to exploit that?','对手预期你会做惯常决定。如何利用这一点？','प्रतिद्वंद्वी आपकी सामान्य चाल की उम्मीद करता है। इसका लाभ कैसे लें?','Tu rival espera tu decisión habitual. ¿Cómo puedes aprovecharlo?'),[O('تغيير النمط في اللحظة المناسبة','Change the pattern at the right moment','在合适时机改变模式','सही समय पर पैटर्न बदलना','Cambiar el patrón en el momento adecuado'),O('كرر نفس القرار دائمًا','Always repeat it','总是重复','हमेशा दोहराना','Repetirlo siempre'),O('أعلن خطتك','Announce your plan','公布计划','योजना बताना','Anunciar tu plan'),O('توقف','Stop','停止','रुकना','Parar')],0,7),
      E(L('ما الفرق بين المخاطرة المحسوبة والمخاطرة العشوائية؟','What is the difference between calculated and random risk?','有计划的风险与随机风险有什么区别？','गणना किए गए जोखिम और यादृच्छिक जोखिम में क्या अंतर है?','¿Cuál es la diferencia entre riesgo calculado y aleatorio?'),[O('المحسوبة تعتمد على معلومات واحتمالات','Calculated risk uses information and probabilities','有计划的风险依赖信息和概率','गणना किया जोखिम जानकारी और संभावनाओं पर निर्भर है','El riesgo calculado usa información y probabilidades'),O('لا فرق','No difference','没有区别','कोई अंतर नहीं','No hay diferencia'),O('العشوائية دائمًا أفضل','Random is always better','随机总是更好','यादृच्छिक हमेशा बेहतर','Lo aleatorio siempre es mejor'),O('المحسوبة بلا مخاطرة','Calculated means no risk','有计划意味着没有风险','गणना का मतलब जोखिम नहीं','Calculado significa sin riesgo')],0,8),
      E(L('لديك خياران: مكسب صغير مضمون أو مكسب كبير باحتمال 30%. ماذا تحتاج قبل الاختيار؟','You have a small guaranteed gain or a large gain with 30% probability. What do you need before choosing?','你可以获得小额保证收益或30%概率的大收益。选择前需要什么？','छोटा निश्चित लाभ या 30% संभावना वाला बड़ा लाभ। चुनने से पहले क्या चाहिए?','Tienes una ganancia pequeña garantizada o una grande con 30%. ¿Qué necesitas antes de elegir?'),[O('قيمة كل مكسب وتكلفة الفشل','Value of each outcome and cost of failure','每种结果的价值与失败成本','हर परिणाम का मूल्य और असफलता की लागत','Valor de cada resultado y coste del fallo'),O('لون الزر','Button color','按钮颜色','बटन का रंग','Color del botón'),O('رأي شخص عشوائي','A random opinion','随机意见','यादृच्छिक राय','Opinión al azar'),O('السرعة فقط','Speed only','只看速度','केवल गति','Solo velocidad')],0,9),
      E(L('في موقف معقد، ما أفضل طريقة لمنع القرار العاطفي؟','In a complex situation, what best prevents an emotional decision?','在复杂情况下，什么最能防止情绪化决策？','जटिल स्थिति में भावनात्मक निर्णय को रोकने का सबसे अच्छा तरीका क्या है?','En una situación compleja, ¿qué ayuda más a evitar una decisión emocional?'),[O('استخدام معايير واضحة قبل الاختيار','Use clear criteria before choosing','选择前设定明确标准','चुनने से पहले स्पष्ट मानदंड','Usar criterios claros antes de elegir'),O('اختيار أول فكرة','Choose the first idea','选择第一个想法','पहला विचार चुनना','Elegir la primera idea'),O('زيادة السرعة','Increase speed','提高速度','गति बढ़ाना','Aumentar la velocidad'),O('تجاهل النتائج','Ignore outcomes','忽略结果','परिणाम अनदेखा करना','Ignorar resultados')],0,9),
      E(L('إذا تغيرت المعلومات أثناء التنفيذ، ما القاعدة الأقوى؟','If information changes during execution, what is the strongest rule?','执行过程中信息变化，最重要的规则是什么？','कार्यान्वयन के दौरान जानकारी बदल जाए तो सबसे मजबूत नियम क्या है?','Si cambia la información durante la ejecución, ¿cuál es la regla más fuerte?'),[O('تعديل القرار بناءً على المعلومات الجديدة','Update the decision using the new information','根据新信息调整决定','नई जानकारी के अनुसार निर्णय बदलना','Actualizar la decisión con la nueva información'),O('التمسك بالخطة مهما حدث','Keep the plan no matter what','无论如何坚持原计划','कुछ भी हो योजना पर टिके रहना','Mantener el plan pase lo que pase'),O('تجاهل التغيير','Ignore the change','忽略变化','बदलाव अनदेखा करना','Ignorar el cambio'),O('إلغاء الهدف دائمًا','Always cancel the goal','总是取消目标','हमेशा लक्ष्य रद्द करना','Cancelar siempre el objetivo')],0,10),
      E(L('أصعب قرار: معلومات ناقصة، وقت قصير، ونتائج مختلفة جدًا. ما أفضل منهج؟','Hardest case: incomplete information, little time, and very different outcomes. What is the best approach?','最难情况：信息不完整、时间很少、结果差异巨大。最佳方法是什么？','सबसे कठिन स्थिति: अधूरी जानकारी, कम समय और बहुत अलग परिणाम। सर्वोत्तम तरीका क्या है?','Caso difícil: información incompleta, poco tiempo y resultados muy distintos. ¿Cuál es el mejor enfoque?'),[O('تحديد أسوأ نتيجة مقبولة ثم اختيار قرار قابل للتعديل','Define an acceptable worst case, then choose a reversible decision','确定可接受的最坏结果，再选择可逆决策','स्वीकार्य सबसे खराब परिणाम तय कर फिर उलटने योग्य निर्णय चुनना','Definir el peor caso aceptable y elegir una decisión reversible'),O('التخمين فقط','Guess only','只猜','केवल अनुमान','Solo adivinar'),O('الانتظار بلا نهاية','Wait forever','无限等待','अनंत प्रतीक्षा','Esperar indefinidamente'),O('اختيار أعلى مخاطرة دائمًا','Always choose highest risk','总是选择最高风险','हमेशा सबसे अधिक जोखिम','Elegir siempre el mayor riesgo')],0,10)
    ]);

  add('reaction','🎯',80,
    ['تحدي رد الفعل','Reaction Challenge','反应挑战','रिएक्शन चैलेंज','Desafío de Reacción'],
    ['قرارات سريعة مع الحفاظ على الدقة.','Fast decisions while preserving accuracy.','在速度中保持准确性。','गति के साथ सटीकता बनाए रखें।','Decisiones rápidas sin perder precisión.'],[
      E(L('إذا ظهر اللون الأحمر، ما الأولوية؟','If red appears, what is the priority?','如果出现红色，优先级是什么？','यदि लाल दिखाई दे, प्राथमिकता क्या है?','Si aparece rojo, ¿cuál es la prioridad?'),[O('السرعة دون تفكير','Speed without thinking','不思考只求速度','बिना सोचे गति','Velocidad sin pensar'),O('التعرف على الإشارة ثم الاستجابة','Recognize the signal then respond','识别信号再反应','संकेत पहचानकर प्रतिक्रिया','Reconocer la señal y responder'),O('الانتظار دائمًا','Always wait','总是等待','हमेशा प्रतीक्षा','Esperar siempre'),O('تجاهل اللون','Ignore the color','忽略颜色','रंग अनदेखा करना','Ignorar el color')],1,1),
      E(L('أي استراتيجية تقلل أخطاء الضغط؟','Which strategy reduces pressure errors?','哪种策略减少压力下的错误？','कौन सी रणनीति दबाव में गलतियाँ कम करती है?','¿Qué estrategia reduce errores bajo presión?'),[O('التنفس والتركيز على الإشارة','Breathe and focus on the signal','呼吸并专注信号','सांस लेकर संकेत पर ध्यान','Respirar y centrarse en la señal'),O('النقر العشوائي','Random clicking','随机点击','यादृच्छिक क्लिक','Clic aleatorio'),O('إغلاق الشاشة','Close the screen','关闭屏幕','स्क्रीन बंद करना','Cerrar la pantalla'),O('تغيير القاعدة كل ثانية','Change the rule every second','每秒改变规则','हर सेकंड नियम बदलना','Cambiar la regla cada segundo')],0,2),
      E(L('السرعة وحدها لا تكفي لأن؟','Speed alone is not enough because?','仅有速度为什么不够？','केवल गति पर्याप्त क्यों नहीं है?','¿Por qué la velocidad sola no basta?'),[O('الدقة جزء من الأداء','Accuracy is part of performance','准确性也是表现的一部分','सटीकता प्रदर्शन का हिस्सा है','La precisión es parte del rendimiento'),O('السرعة سيئة دائمًا','Speed is always bad','速度总是不好','गति हमेशा खराब है','La velocidad siempre es mala'),O('الأسئلة لا تحتاج إجابة','Questions need no answer','问题不需要答案','सवालों का उत्तर नहीं चाहिए','Las preguntas no necesitan respuesta'),O('الوقت لا يهم','Time never matters','时间不重要','समय मायने नहीं रखता','El tiempo nunca importa')],0,3),
      E(L('عندما تتشابه الإشارات، ما المهارة الأهم؟','When signals look similar, what skill matters most?','当信号相似时，什么技能最重要？','जब संकेत समान दिखें, कौन सा कौशल सबसे महत्वपूर्ण है?','Cuando las señales se parecen, ¿qué habilidad importa más?'),[O('تمييز التفاصيل','Discriminating details','区分细节','विवरण पहचानना','Distinguir detalles'),O('الضغط الأسرع دائمًا','Always pressing fastest','总是最快点击','हमेशा सबसे तेज़ क्लिक','Pulsar siempre más rápido'),O('التخمين','Guessing','猜测','अनुमान','Adivinar'),O('تجاهل الإشارة','Ignore the signal','忽略信号','संकेत अनदेखा करना','Ignorar la señal')],0,4),
      E(L('أفضل رد فعل ليس الأسرع دائمًا؛ بل؟','The best reaction is not always the fastest; it is?','最佳反应不总是最快，而是？','सबसे अच्छी प्रतिक्रिया हमेशा सबसे तेज़ नहीं; बल्कि?','La mejor reacción no siempre es la más rápida; es?'),[O('الأسرع الصحيح','The fastest correct one','最快且正确','सबसे तेज़ सही प्रतिक्रिया','La más rápida y correcta'),O('الأبطأ','The slowest','最慢','सबसे धीमी','La más lenta'),O('العشوائي','Random','随机','यादृच्छिक','Aleatoria'),O('غير المرتبط بالإشارة','Unrelated to the signal','与信号无关','संकेत से असंबंधित','Sin relación con la señal')],0,5),
      E(L('إذا ارتفع معدل الأخطاء بعد زيادة السرعة، ماذا تفعل؟','If errors rise after increasing speed, what do you do?','提高速度后错误增加，怎么办？','गति बढ़ाने पर गलतियाँ बढ़ें तो क्या करें?','Si aumentan los errores al acelerar, ¿qué haces?'),[O('أبطئ قليلًا لاستعادة الدقة','Slow slightly to regain accuracy','稍微减速恢复准确性','सटीकता पाने के लिए थोड़ा धीमा','Reducir un poco para recuperar precisión'),O('أسرع أكثر','Go faster','更快','और तेज़','Acelerar más'),O('أوقف التحدي','Stop the challenge','停止挑战','चैलेंज रोकें','Detener el desafío'),O('أغير الإجابة عشوائيًا','Change answers randomly','随机改答案','उत्तर बेतरतीब बदलना','Cambiar respuestas al azar')],0,6),
      E(L('الاستجابة الحركية تتأثر بالتوقع. ماذا يعني ذلك؟','Motor response is affected by anticipation. What does that mean?','运动反应受预期影响。这意味着什么？','मोटर प्रतिक्रिया प्रत्याशा से प्रभावित होती है। इसका क्या अर्थ है?','La respuesta motora se ve afectada por la anticipación. ¿Qué significa?'),[O('قد تستجيب قبل ظهور الإشارة','You may respond before the signal appears','可能在信号出现前反应','संकेत से पहले प्रतिक्रिया हो सकती है','Puedes responder antes de que aparezca la señal'),O('لا علاقة للتوقع','Anticipation has no role','预期没有作用','प्रत्याशा की कोई भूमिका नहीं','No influye'),O('التوقع يلغي الدقة دائمًا','Anticipation always removes accuracy','预期总会消除准确性','प्रत्याशा हमेशा सटीकता खत्म करती है','La anticipación siempre elimina precisión'),O('لا توجد إشارات','There are no signals','没有信号','कोई संकेत नहीं','No hay señales')],0,7),
      E(L('في تحدٍ عالي السرعة، لماذا تساعد قاعدة ثابتة؟','In a high-speed challenge, why does a fixed rule help?','高速挑战中，固定规则为什么有帮助？','तेज़ चैलेंज में स्थिर नियम क्यों मदद करता है?','En un desafío rápido, ¿por qué ayuda una regla fija?'),[O('تقلل الحمل الذهني','It reduces mental load','降低认知负荷','मानसिक भार कम करता है','Reduce la carga mental'),O('تزيد التشتيت','It increases distraction','增加分心','ध्यान भटकाता है','Aumenta la distracción'),O('تمنع التفكير','It prevents thinking','阻止思考','सोच रोकता है','Impide pensar'),O('لا فائدة لها','It has no benefit','没有好处','कोई लाभ नहीं','No tiene beneficio')],0,8),
      E(L('عندما تكون الإشارة خادعة، ما الأولوية؟','When a signal is deceptive, what is the priority?','当信号具有欺骗性时，优先考虑什么？','जब संकेत भ्रामक हो तो प्राथमिकता क्या है?','Cuando una señal es engañosa, ¿qué es prioritario?'),[O('اتباع القاعدة لا الانطباع','Follow the rule, not the impression','遵循规则而不是直觉印象','धारणा नहीं, नियम का पालन','Seguir la regla, no la impresión'),O('التخمين','Guess','猜测','अनुमान','Adivinar'),O('السرعة بأي ثمن','Speed at any cost','不惜一切代价追求速度','किसी भी कीमत पर गति','Velocidad a cualquier precio'),O('تغيير القاعدة','Change the rule','改变规则','नियम बदलना','Cambiar la regla')],0,9),
      E(L('إذا حققت 95% دقة بسرعة متوسطة مقابل 70% بسرعة قصوى، أي أداء أقوى؟','If you achieve 95% accuracy at medium speed versus 70% at maximum speed, which is stronger performance?','中速准确率95%与极速准确率70%，哪种表现更强？','मध्यम गति पर 95% सटीकता बनाम अधिकतम गति पर 70%, कौन सा बेहतर है?','95% de precisión a velocidad media frente a 70% a velocidad máxima: ¿qué rendimiento es mejor?'),[O('95% مع السرعة المتوسطة','95% at medium speed','中速95%','मध्यम गति पर 95%','95% a velocidad media'),O('70% دائمًا','70% always','70%总是更好','70% हमेशा','70% siempre'),O('لا يمكن المقارنة','Cannot compare','无法比较','तुलना नहीं','No se puede comparar'),O('السرعة القصوى فقط','Maximum speed only','只看最大速度','केवल अधिकतम गति','Solo velocidad máxima')],0,10),
      E(L('الاختبار الأصعب يجمع سرعة الإشارة ودقة القرار. ما المبدأ النهائي؟','The hardest test combines signal speed and decision accuracy. What is the final principle?','最难测试结合信号速度与决策准确性。最终原则是什么？','सबसे कठिन परीक्षण संकेत की गति और निर्णय की सटीकता जोड़ता है। अंतिम सिद्धांत क्या है?','La prueba más difícil combina velocidad de señal y precisión de decisión. ¿Cuál es el principio final?'),[O('السرعة المفيدة = سرعة + دقة','Useful speed = speed + accuracy','有效速度 = 速度 + 准确性','उपयोगी गति = गति + सटीकता','Velocidad útil = velocidad + precisión'),O('السرعة فقط','Speed only','只要速度','केवल गति','Solo velocidad'),O('الدقة فقط','Accuracy only','只要准确','केवल सटीकता','Solo precisión'),O('الحظ','Luck','运气','भाग्य','Suerte')],0,10)
    ]);

  C.getAll=()=>Object.values(C).filter(x=>x&&typeof x==='object'&&x.questions&&!x.special);
  window.dispatchEvent(new CustomEvent('zivozone-challenges-ready',{detail:{count:C.getAll().length}}));
})();
