/* ============================================================
   ZIVOZONE CHALLENGE BANK
   4 core challenges × 10 questions
   Every question and answer is localized in 5 languages.
============================================================ */
(() => {
  'use strict';
  const q=(ar,en,zh,hi,es,arA,enA,zhA,hiA,esA,c,d)=>({q:{ar,en,zh,hi,es},a:arA.map((_,i)=>({ar:arA[i],en:enA[i],zh:zhA[i],hi:hiA[i],es:esA[i]})),c,d});
  const A=(ar,en,zh,hi,es)=>({ar,en,zh,hi,es});
  const bank={
    iq:{id:'iq',icon:'🧠',xp:80,title:A('اختبار سرعة الذكاء','Rapid IQ Challenge','极速智力挑战','तेज़ IQ चैलेंज','Desafío de IQ rápido'),desc:A('10 أسئلة تتدرج من السهل إلى الصعب جدًا.','10 questions from easy to extremely hard.','10道题，从简单逐步提升到极难。','10 सवाल, आसान से बेहद कठिन तक।','10 preguntas de fáciles a extremadamente difíciles.'),questions:[
      q('ما العدد التالي: 2، 4، 8، 16، ؟','What comes next: 2, 4, 8, 16, ?','下一个数字是什么：2、4、8、16、？','अगली संख्या क्या है: 2, 4, 8, 16, ?','¿Qué número sigue: 2, 4, 8, 16, ?',['20','24','32','36'],['20','24','32','36'],['20','24','32','36'],['20','24','32','36'],['20','24','32','36'],2,1),
      q('أي كلمة مختلفة عن البقية؟','Which word is different?','哪个词与其他词不同？','कौन सा शब्द अलग है?','¿Qué palabra es diferente?',['تفاحة','موزة','برتقالة','سيارة'],['Apple','Banana','Orange','Car'],['苹果','香蕉','橙子','汽车'],['सेब','केला','संतरा','कार'],['Manzana','Plátano','Naranja','Coche'],3,1),
      q('إذا كان اليوم الاثنين، فما اليوم بعد 10 أيام؟','If today is Monday, what day is it after 10 days?','如果今天是星期一，10天后是星期几？','यदि आज सोमवार है, तो 10 दिन बाद कौन सा दिन होगा?','Si hoy es lunes, ¿qué día será dentro de 10 días?',['الأربعاء','الخميس','الجمعة','السبت'],['Wednesday','Thursday','Friday','Saturday'],['星期三','星期四','星期五','星期六'],['बुधवार','गुरुवार','शुक्रवार','शनिवार'],['Miércoles','Jueves','Viernes','Sábado'],1,2),
      q('ما نصف 50؟','What is half of 50?','50的一半是多少？','50 का आधा कितना है?','¿Cuál es la mitad de 50?',['15','20','25','30'],['15','20','25','30'],['15','20','25','30'],['15','20','25','30'],['15','20','25','30'],2,1),
      q('أي رقم أولي؟','Which number is prime?','哪个数字是质数？','कौन सी संख्या अभाज्य है?','¿Qué número es primo?',['9','15','17','21'],['9','15','17','21'],['9','15','17','21'],['9','15','17','21'],['9','15','17','21'],2,3),
      q('3، 6، 12، 24، ؟','3, 6, 12, 24, ?','3、6、12、24、？','3, 6, 12, 24, ?','3, 6, 12, 24, ¿?',['36','42','48','54'],['36','42','48','54'],['36','42','48','54'],['36','42','48','54'],['36','42','48','54'],2,6),
      q('إذا كانت كل A هي B وبعض B هي C، فما المؤكد؟','If every A is B and some B are C, what is certain?','如果所有A都是B，而部分B是C，什么一定成立？','यदि हर A, B है और कुछ B, C हैं, तो क्या निश्चित है?','Si todo A es B y algunos B son C, ¿qué es seguro?',['كل A هي C','بعض A هي C','كل A هي B','لا توجد B'],['Every A is C','Some A are C','Every A is B','There are no B'],['所有A都是C','部分A是C','所有A都是B','不存在B'],['हर A, C है','कुछ A, C हैं','हर A, B है','कोई B नहीं'],['Todo A es C','Algunos A son C','Todo A es B','No hay B'],2,7),
      q('ما العدد الذي يكمل النمط: 1، 4، 9، 16، 25، ؟','Which number completes: 1, 4, 9, 16, 25, ?','补全序列：1、4、9、16、25、？','पैटर्न पूरा करें: 1, 4, 9, 16, 25, ?','Completa la secuencia: 1, 4, 9, 16, 25, ¿?',['30','36','40','49'],['30','36','40','49'],['30','36','40','49'],['30','36','40','49'],['30','36','40','49'],1,8),
      q('ساعة تتقدم 5 دقائق كل ساعة. بعد 12 ساعة، كم دقيقة تتقدم؟','A clock gains 5 minutes every hour. How many minutes does it gain after 12 hours?','一只钟每小时快5分钟，12小时后快多少分钟？','एक घड़ी हर घंटे 5 मिनट आगे होती है। 12 घंटे बाद कितने मिनट आगे होगी?','Un reloj adelanta 5 minutos por hora. ¿Cuántos minutos adelantará después de 12 horas?',['50','55','60','65'],['50','55','60','65'],['50','55','60','65'],['50','55','60','65'],['50','55','60','65'],2,9),
      q('إذا كان 2=6، 3=12، 4=20، فـ 5 = ؟','If 2=6, 3=12, 4=20, then 5 = ?','如果2=6、3=12、4=20，那么5等于多少？','यदि 2=6, 3=12, 4=20, तो 5 = ?','Si 2=6, 3=12, 4=20, entonces 5 = ?',['25','30','35','40'],['25','30','35','40'],['25','30','35','40'],['25','30','35','40'],['25','30','35','40'],1,10)
    ]},
    science:{id:'science',icon:'🔬',xp:70,title:A('تحدي العلوم','Science Challenge','科学挑战','साइंस चैलेंज','Desafío de ciencia'),desc:A('10 أسئلة علمية بتصعيد حقيقي.','10 science questions with real difficulty scaling.','10道科学题，难度逐步提升。','10 विज्ञान प्रश्न, कठिनाई बढ़ती हुई।','10 preguntas científicas con dificultad progresiva.'),questions:[
      q('ما الكوكب المعروف بالكوكب الأحمر؟','Which planet is known as the Red Planet?','哪颗行星被称为红色星球？','किस ग्रह को लाल ग्रह कहा जाता है?','¿Qué planeta es conocido como el Planeta Rojo?',['الأرض','المريخ','الزهرة','المشتري'],['Earth','Mars','Venus','Jupiter'],['地球','火星','金星','木星'],['पृथ्वी','मंगल','शुक्र','बृहस्पति'],['Tierra','Marte','Venus','Júpiter'],1,1),
      q('ما الغاز الضروري للتنفس عند الإنسان؟','Which gas is essential for human respiration?','人类呼吸需要哪种气体？','मानव श्वसन के लिए कौन सी गैस आवश्यक है?','¿Qué gas es esencial para la respiración humana?',['الأكسجين','الهيليوم','الهيدروجين','النيون'],['Oxygen','Helium','Hydrogen','Neon'],['氧气','氦气','氢气','氖气'],['ऑक्सीजन','हीलियम','हाइड्रोजन','नियॉन'],['Oxígeno','Helio','Hidrógeno','Neón'],0,1),
      q('كم عدد قارات العالم وفق التقسيم الشائع؟','How many continents are commonly recognized?','通常认为世界有多少个大洲？','आम तौर पर कितने महाद्वीप माने जाते हैं?','¿Cuántos continentes se reconocen comúnmente?',['5','6','7','8'],['5','6','7','8'],['5','6','7','8'],['5','6','7','8'],['5','6','7','8'],2,2),
      q('ما أقرب نجم إلى الأرض؟','What is the closest star to Earth?','离地球最近的恒星是什么？','पृथ्वी के सबसे निकट का तारा कौन सा है?','¿Cuál es la estrella más cercana a la Tierra?',['القمر','الشمس','الشعرى','القطب'],['Moon','Sun','Sirius','Polaris'],['月球','太阳','天狼星','北极星'],['चंद्रमा','सूर्य','सिरियस','ध्रुव तारा'],['Luna','Sol','Sirio','Polaris'],1,2),
      q('أي عضو يضخ الدم؟','Which organ pumps blood?','哪个器官负责泵血？','कौन सा अंग रक्त पंप करता है?','¿Qué órgano bombea la sangre?',['الرئة','الكبد','القلب','المعدة'],['Lung','Liver','Heart','Stomach'],['肺','肝脏','心脏','胃'],['फेफड़ा','यकृत','हृदय','पेट'],['Pulmón','Hígado','Corazón','Estómago'],2,3),
      q('ما وحدة قياس القوة في النظام الدولي؟','What is the SI unit of force?','国际单位制中力的单位是什么？','SI में बल की इकाई क्या है?','¿Cuál es la unidad SI de fuerza?',['جول','واط','نيوتن','باسكال'],['Joule','Watt','Newton','Pascal'],['焦耳','瓦特','牛顿','帕斯卡'],['जूल','वाट','न्यूटन','पास्कल'],['Julio','Vatio','Newton','Pascal'],2,6),
      q('أي جزء من الخلية يحتوي عادةً على المادة الوراثية في الخلايا حقيقية النواة؟','Which cell part usually contains genetic material in eukaryotic cells?','真核细胞中通常含有遗传物质的部分是什么？','यूकैरियोटिक कोशिकाओं में आनुवंशिक पदार्थ सामान्यतः कहाँ होता है?','¿Qué parte de la célula suele contener el material genético en células eucariotas?',['النواة','الغشاء','الجدار','الريبوسوم'],['Nucleus','Membrane','Wall','Ribosome'],['细胞核','细胞膜','细胞壁','核糖体'],['नाभिक','झिल्ली','भित्ति','राइबोसोम'],['Núcleo','Membrana','Pared','Ribosoma'],0,7),
      q('ما الظاهرة التي تفسر انحراف الضوء عند انتقاله بين وسطين؟','Which phenomenon explains light bending when it passes between media?','光从一种介质进入另一种介质时发生偏折的现象是什么？','प्रकाश के दो माध्यमों के बीच जाने पर मुड़ने की घटना क्या कहलाती है?','¿Qué fenómeno explica la desviación de la luz al pasar entre medios?',['الحيود','الانكسار','الانعكاس','التشتت'],['Diffraction','Refraction','Reflection','Dispersion'],['衍射','折射','反射','色散'],['विवर्तन','अपवर्तन','परावर्तन','प्रकीर्णन'],['Difracción','Refracción','Reflexión','Dispersión'],1,8),
      q('أي جسيم يرتبط بالعدد الذري للعنصر؟','Which particle determines an element’s atomic number?','哪种粒子决定元素的原子序数？','कौन सा कण तत्व की परमाणु संख्या निर्धारित करता है?','¿Qué partícula determina el número atómico de un elemento?',['النيوترون','الإلكترون','البروتون','الفوتون'],['Neutron','Electron','Proton','Photon'],['中子','电子','质子','光子'],['न्यूट्रॉन','इलेक्ट्रॉन','प्रोटॉन','फोटॉन'],['Neutrón','Electrón','Protón','Fotón'],2,9),
      q('في نظام معزول مثالي، ما الذي يبقى محفوظًا في التفاعلات الفيزيائية؟','In an ideal isolated system, what is conserved in physical interactions?','在理想孤立系统中，物理相互作用中什么保持守恒？','एक आदर्श पृथक तंत्र में भौतिक अंतःक्रियाओं में क्या संरक्षित रहता है?','En un sistema aislado ideal, ¿qué se conserva en las interacciones físicas?',['الطاقة','اللون','الحجم دائمًا','درجة الحرارة دائمًا'],['Energy','Color','Volume always','Temperature always'],['能量','颜色','体积始终','温度始终'],['ऊर्जा','रंग','आयतन हमेशा','तापमान हमेशा'],['Energía','Color','Volumen siempre','Temperatura siempre'],0,10)
    ]},
    daily:{id:'daily',icon:'⚡',xp:40,title:A('تحدي ZIVO اليومي','ZIVO Daily Challenge','ZIVO 每日挑战','ZIVO डेली चैलेंज','Desafío diario ZIVO'),desc:A('10 أسئلة جديدة بنمط سريع.','10 fresh fast-paced questions.','10道全新的快速问题。','10 नए तेज़ सवाल।','10 preguntas rápidas nuevas.'),questions:[
      q('كم يساوي 15 + 27؟','What is 15 + 27?','15 + 27 等于多少？','15 + 27 कितना है?','¿Cuánto es 15 + 27?',['32','42','52','62'],['32','42','52','62'],['32','42','52','62'],['32','42','52','62'],['32','42','52','62'],1,1),
      q('ما عاصمة الأردن؟','What is the capital of Jordan?','约旦的首都是什么？','जॉर्डन की राजधानी क्या है?','¿Cuál es la capital de Jordania?',['عمّان','إربد','العقبة','الزرقاء'],['Amman','Irbid','Aqaba','Zarqa'],['安曼','伊尔比德','亚喀巴','扎尔卡'],['अम्मान','इरबिद','अकाबा','ज़रका'],['Amán','Irbid','Áqaba','Zarqa'],0,1),
      q('كم عدد أيام الأسبوع؟','How many days are in a week?','一周有几天？','एक सप्ताह में कितने दिन होते हैं?','¿Cuántos días tiene una semana?',['5','6','7','8'],['5','6','7','8'],['5','6','7','8'],['5','6','7','8'],['5','6','7','8'],2,1),
      q('كم دقيقة في الساعة؟','How many minutes are in an hour?','一小时有多少分钟？','एक घंटे में कितने मिनट होते हैं?','¿Cuántos minutos tiene una hora?',['30','45','60','90'],['30','45','60','90'],['30','45','60','90'],['30','45','60','90'],['30','45','60','90'],2,2),
      q('ما أكبر محيط على الأرض؟','What is the largest ocean on Earth?','地球上最大的海洋是什么？','पृथ्वी का सबसे बड़ा महासागर कौन सा है?','¿Cuál es el océano más grande de la Tierra?',['الأطلسي','الهندي','الهادئ','المتجمد'],['Atlantic','Indian','Pacific','Arctic'],['大西洋','印度洋','太平洋','北冰洋'],['अटलांटिक','हिंद महासागर','प्रशांत','आर्कटिक'],['Atlántico','Índico','Pacífico','Ártico'],2,3),
      q('إذا كان لديك 4 صناديق في كل منها 6 كرات، كم كرة لديك؟','If you have 4 boxes with 6 balls each, how many balls do you have?','4个箱子，每箱6个球，一共有多少个球？','4 डिब्बों में प्रत्येक में 6 गेंदें हैं। कुल कितनी गेंदें हैं?','Si tienes 4 cajas con 6 pelotas cada una, ¿cuántas pelotas tienes?',['10','18','24','30'],['10','18','24','30'],['10','18','24','30'],['10','18','24','30'],['10','18','24','30'],2,5),
      q('أي كسر يساوي 0.75؟','Which fraction equals 0.75?','哪个分数等于0.75？','कौन सा भिन्न 0.75 के बराबर है?','¿Qué fracción equivale a 0.75?',['1/2','2/3','3/4','4/5'],['1/2','2/3','3/4','4/5'],['1/2','2/3','3/4','4/5'],['1/2','2/3','3/4','4/5'],['1/2','2/3','3/4','4/5'],2,6),
      q('ما العدد التالي: 5، 10، 20، 40، ؟','What comes next: 5, 10, 20, 40, ?','下一个数字是什么：5、10、20、40、？','अगली संख्या क्या है: 5, 10, 20, 40, ?','¿Qué sigue: 5, 10, 20, 40, ?',['60','70','80','100'],['60','70','80','100'],['60','70','80','100'],['60','70','80','100'],['60','70','80','100'],2,7),
      q('إذا زاد سعر 200 بنسبة 15%، يصبح؟','If a price of 200 increases by 15%, what does it become?','200的价格增加15%后是多少？','200 की कीमत 15% बढ़ने पर कितनी होगी?','Si un precio de 200 aumenta un 15%, ¿en cuánto queda?',['215','225','230','240'],['215','225','230','240'],['215','225','230','240'],['215','225','230','240'],['215','225','230','240'],2,8),
      q('لديك 3 محاولات، في كل محاولة احتمال نجاح مستقل 50%. ما احتمال نجاح محاولة واحدة على الأقل؟','You have 3 independent attempts, each with a 50% success chance. What is the chance of at least one success?','有3次独立尝试，每次成功概率为50%，至少成功一次的概率是多少？','3 स्वतंत्र प्रयास हैं, हर प्रयास की सफलता की संभावना 50% है। कम से कम एक बार सफल होने की संभावना क्या है?','Tienes 3 intentos independientes, cada uno con 50% de éxito. ¿Cuál es la probabilidad de al menos un éxito?',['50%','62.5%','75%','87.5%'],['50%','62.5%','75%','87.5%'],['50%','62.5%','75%','87.5%'],['50%','62.5%','75%','87.5%'],['50%','62.5%','75%','87.5%'],3,10)
    ]},
    horror:{id:'horror',icon:'👻',xp:120,special:true,title:A('الغرفة المظلمة','The Dark Room','黑暗房间','डार्क रूम','La Habitación Oscura'),desc:A('10 مراحل نفسية مع تصعيد تدريجي وحارس غامض.','10 psychological stages with a gradual escalation and a mysterious warden.','10个逐渐升级的心理阶段，还有神秘守卫。','10 मनोवैज्ञानिक चरण और एक रहस्यमय गार्ड।','10 etapas psicológicas con escalada y un guardián misterioso.'),questions:[
      q('الضوء يختفي لثانيتين. أمامك بابان: أحدهما يحمل علامة Z والآخر بلا علامة. ماذا تختار؟','The light disappears for two seconds. Two doors remain: one marked Z and one unmarked. What do you choose?','灯光消失两秒。面前有两扇门：一扇有Z标记，另一扇没有。你选哪扇？','रोशनी दो सेकंड के लिए गायब हो जाती है। दो दरवाज़े हैं: एक पर Z है और दूसरा खाली है। आप क्या चुनेंगे?','La luz desaparece durante dos segundos. Hay dos puertas: una con Z y otra sin marca. ¿Cuál eliges?',['باب Z','الباب الآخر'],['Door Z','The other door'],['Z门','另一扇门'],['Z वाला दरवाज़ा','दूसरा दरवाज़ा'],['Puerta Z','La otra puerta'],0,1),
      q('تسمع ثلاث طرقات من خلفك. ما أول شيء تفعله؟','You hear three knocks behind you. What is the first thing you do?','你听到身后三声敲门声。第一件事做什么？','आप अपने पीछे तीन दस्तक सुनते हैं। सबसे पहले क्या करेंगे?','Escuchas tres golpes detrás de ti. ¿Qué haces primero?',['ألتفت فورًا','أثبت مكاني وأراقب','أركض عشوائيًا','أغلق عيني'],['Turn immediately','Stay still and observe','Run randomly','Close my eyes'],['立即转身','站住并观察','随意奔跑','闭上眼睛'],['तुरंत मुड़ता हूँ','स्थिर रहकर देखता हूँ','बेतरतीब दौड़ता हूँ','आँखें बंद करता हूँ'],['Me giro de inmediato','Me quedo quieto y observo','Corro al azar','Cierro los ojos'],1,2),
      q('وجدت مفتاحًا باردًا على الأرض. ماذا تفعل؟','You find a cold key on the floor. What do you do?','你在地上发现一把冰冷的钥匙。你会怎么做？','आपको ज़मीन पर एक ठंडी चाबी मिलती है। क्या करेंगे?','Encuentras una llave fría en el suelo. ¿Qué haces?',['أستخدمه فورًا','أفحصه قبل استخدامه','أتركه وأصرخ','أكسره'],['Use it immediately','Inspect it before using it','Leave it and scream','Break it'],['立即使用','使用前检查','丢下并尖叫','把它弄坏'],['तुरंत इस्तेमाल','इस्तेमाल से पहले जाँच','छोड़कर चिल्लाना','तोड़ देना'],['Usarla de inmediato','Inspeccionarla antes de usarla','Dejarla y gritar','Romperla'],1,3),
      q('على الجدار سهمان: أحدهما مضاء والآخر مظلم. أيهما تتبع؟','Two arrows are on the wall: one lit and one dark. Which do you follow?','墙上有两个箭头：一个亮着，一个在黑暗中。你跟哪一个？','दीवार पर दो तीर हैं: एक रोशन और एक अंधेरा। किसका पीछा करेंगे?','Hay dos flechas en la pared: una iluminada y otra oscura. ¿Cuál sigues?',['المضاء','المظلم'],['The lit one','The dark one'],['亮着的','黑暗的'],['रोशन वाला','अंधेरा वाला'],['La iluminada','La oscura'],0,4),
      q('تسمع صوتًا يقول: «لا تفتح الباب». ماذا تفعل؟','A voice says: “Do not open the door.” What do you do?','一个声音说：“不要开门。”你会怎么做？','एक आवाज़ कहती है: “दरवाज़ा मत खोलो।” क्या करेंगे?','Una voz dice: “No abras la puerta”. ¿Qué haces?',['أفتح فورًا','أبحث عن مصدر الصوت أولًا','أكسر الباب','أهرب دون تفكير'],['Open immediately','Find the source of the voice first','Break the door','Run without thinking'],['立即打开','先寻找声音来源','撞开门','不假思索地逃跑'],['तुरंत खोलना','पहले आवाज़ का स्रोत ढूँढना','दरवाज़ा तोड़ना','बिना सोचे भागना'],['Abrir de inmediato','Buscar primero el origen de la voz','Romper la puerta','Huir sin pensar'],1,5),
      q('الممر يتفرع إلى 3 طرق، وتوجد آثار أقدام في طريق واحد فقط. ماذا تستنتج؟','The corridor splits into three paths, and footprints appear on only one. What can you conclude?','走廊分成三条路，只有一条有脚印。你能得出什么结论？','गलियारा तीन रास्तों में बँटता है और केवल एक पर पैरों के निशान हैं। आप क्या निष्कर्ष निकालेंगे?','El pasillo se divide en tres caminos y solo uno tiene huellas. ¿Qué concluyes?',['الطريق آمن','هناك شخص مر من هناك','الآثار مزيفة بالتأكيد','لا يمكن معرفة شيء'],['The path is safe','Someone passed there','The footprints are definitely fake','Nothing can be known'],['这条路安全','有人经过那里','脚印肯定是假的','无法知道任何事'],['रास्ता सुरक्षित है','वहाँ से कोई गुज़रा','निशान निश्चित रूप से नकली हैं','कुछ भी पता नहीं'],['El camino es seguro','Alguien pasó por allí','Las huellas son falsas con certeza','No se puede saber nada'],1,6),
      q('ساعة متوقفة عند 03:17، والرسالة تقول: «الوقت ليس كما تراه». ما أفضل قرار؟','A clock is stuck at 03:17 and a message says: “Time is not what you see.” What is the best decision?','时钟停在03:17，信息写着：“时间并不是你看到的样子。”最佳决定是什么？','घड़ी 03:17 पर रुकी है और संदेश कहता है: “समय वैसा नहीं है जैसा तुम देखते हो।” सबसे अच्छा निर्णय क्या है?','Un reloj está detenido a las 03:17 y un mensaje dice: “El tiempo no es lo que ves”. ¿Cuál es la mejor decisión?',['أثق بالساعة','أبحث عن مصدر مستقل للمعلومة','أضبطها على 03:17','أتجاهل كل شيء'],['Trust the clock','Look for an independent source of information','Set it to 03:17','Ignore everything'],['相信时钟','寻找独立的信息来源','把它调到03:17','忽略一切'],['घड़ी पर भरोसा','जानकारी का स्वतंत्र स्रोत ढूँढना','इसे 03:17 पर सेट करना','सब कुछ अनदेखा करना'],['Confiar en el reloj','Buscar una fuente independiente de información','Ponerlo a las 03:17','Ignorarlo todo'],1,7),
      q('الحارس يظهر ويقول: «إذا أجبت بسرعة ستخسر». ماذا تفعل؟','The warden appears and says: “If you answer quickly, you lose.” What do you do?','守卫出现并说：“如果你回答太快，你就会输。”你怎么办？','गार्ड कहता है: “अगर तुम जल्दी जवाब दोगे तो हार जाओगे।” क्या करेंगे?','El guardián aparece y dice: “Si respondes rápido, pierdes”. ¿Qué haces?',['أجيب فورًا','أطلب إعادة السؤال بهدوء','أهرب','أغمض عيني'],['Answer immediately','Ask for the question to be repeated calmly','Run away','Close my eyes'],['立即回答','冷静地要求重复问题','逃跑','闭上眼睛'],['तुरंत जवाब','शांत होकर सवाल दोहराने को कहना','भागना','आँखें बंद करना'],['Responder de inmediato','Pedir que repita la pregunta con calma','Huir','Cerrar los ojos'],1,8),
      q('يقول الحارس: «الإجابة الصحيحة ليست التي تبدو صحيحة». أي مهارة تحتاج الآن؟','The warden says: “The correct answer is not the one that looks correct.” What skill do you need now?','守卫说：“正确答案并不是看起来正确的那个。”你现在需要什么能力？','गार्ड कहता है: “सही उत्तर वह नहीं जो सही दिखाई दे।” अब किस कौशल की जरूरत है?','El guardián dice: “La respuesta correcta no es la que parece correcta”. ¿Qué habilidad necesitas?',['التسرع','التحقق من الافتراضات','الحظ','الصوت العالي'],['Rushing','Checking assumptions','Luck','Loudness'],['仓促','检查假设','运气','大声说话'],['जल्दबाज़ी','मान्यताओं की जाँच','भाग्य','ऊँची आवाज़'],['Prisa','Comprobar las suposiciones','Suerte','Hablar fuerte'],1,9),
      q('آخر باب لا يفتح إلا إذا اخترت بين الخروج الآن أو معرفة الحقيقة. ماذا تختار؟','The final door opens only if you choose between leaving now or knowing the truth. What do you choose?','最后一扇门只有在“现在离开”或“知道真相”之间做出选择后才会打开。你选什么？','अंतिम दरवाज़ा तभी खुलता है जब आप अभी बाहर निकलने या सच्चाई जानने में से चुनें। क्या चुनेंगे?','La última puerta solo se abre si eliges entre salir ahora o conocer la verdad. ¿Qué eliges?',['الخروج','معرفة الحقيقة'],['Leave','Know the truth'],['离开','知道真相'],['बाहर निकलना','सच्चाई जानना'],['Salir','Conocer la verdad'],1,10)
    ]}
  };

  // ------------------------------------------------------------
  // EXPANSION POOL: extra questions are selected dynamically so a
  // player does not receive the exact same 10-question session.
  // Every question keeps the same 1-10 difficulty scale.
  // ------------------------------------------------------------
  const E=(q,opts,c,d)=>({q,a:opts,c,d});
  const L=(ar,en,zh,hi,es)=>({ar,en,zh,hi,es});
  const O=(ar,en,zh,hi,es)=>L(ar,en,zh,hi,es);

  bank.iq.questions.push(
    E(L('ما العدد التالي: 1، 3، 6، 10، 15، ؟','What comes next: 1, 3, 6, 10, 15, ?','下一个数字是什么：1、3、6、10、15、？','अगली संख्या क्या है: 1, 3, 6, 10, 15, ?','¿Qué sigue: 1, 3, 6, 10, 15, ?'),[O('18','18','18','18','18'),O('20','20','20','20','20'),O('21','21','21','21','21'),O('22','22','22','22','22')],2,5),
    E(L('إذا كانت كل الورود زهورًا وبعض الزهور تذبل، فما العبارة المؤكدة؟','If all roses are flowers and some flowers wilt, what is certain?','如果所有玫瑰都是花，而且有些花会凋谢，什么一定成立？','यदि सभी गुलाब फूल हैं और कुछ फूल मुरझाते हैं, तो क्या निश्चित है?','Si todas las rosas son flores y algunas flores se marchitan, ¿qué es seguro?'),[O('كل الورود تذبل','All roses wilt','所有玫瑰都会凋谢','सभी गुलाब मुरझाते हैं','Todas las rosas se marchitan'),O('بعض الورود تذبل','Some roses wilt','一些玫瑰会凋谢','कुछ गुलाब मुरझाते हैं','Algunas rosas se marchitan'),O('كل الورود زهور','All roses are flowers','所有玫瑰都是花','सभी गुलाब फूल हैं','Todas las rosas son flores'),O('لا توجد زهور','There are no flowers','不存在花','कोई फूल नहीं हैं','No hay flores')],2,4),
    E(L('ثلاثة أشخاص يجلسون في صف. ليلى ليست في الطرف، وسامي يجلس يسار عمر. من في الوسط؟','Three people sit in a row. Layla is not at an end, and Sami sits left of Omar. Who is in the middle?','三个人排成一列。Layla不在两端，Sami坐在Omar左边。谁在中间？','तीन लोग पंक्ति में बैठे हैं। लैला किनारे पर नहीं है और सामी उमर के बाईं ओर है। बीच में कौन है?','Tres personas se sientan en fila. Layla no está en un extremo y Sami está a la izquierda de Omar. ¿Quién está en medio?'),[O('ليلى','Layla','Layla','लैला','Layla'),O('سامي','Sami','Sami','सामी','Sami'),O('عمر','Omar','Omar','उमर','Omar'),O('لا يمكن تحديده','Cannot determine','无法确定','निर्धारित नहीं किया जा सकता','No se puede determinar')],0,7),
    E(L('إذا كان بعض اللاعبين أسرع من خالد، وخالد أسرع من مازن، فما الذي يمكن أن يكون صحيحًا؟','If some players are faster than Khaled, and Khaled is faster than Mazen, what can be true?','如果一些球员比Khaled快，而Khaled比Mazen快，什么可能成立？','यदि कुछ खिलाड़ी खालिद से तेज हैं और खालिद माज़ेन से तेज है, तो क्या सही हो सकता है?','Si algunos jugadores son más rápidos que Khaled y Khaled es más rápido que Mazen, ¿qué puede ser cierto?'),[O('مازن أسرع من الجميع','Mazen is faster than everyone','Mazen比所有人都快','माज़ेन सबसे तेज है','Mazen es más rápido que todos'),O('خالد أبطأ من مازن','Khaled is slower than Mazen','Khaled比Mazen慢','खालिद माज़ेन से धीमा है','Khaled es más lento que Mazen'),O('بعض اللاعبين أسرع من مازن','Some players are faster than Mazen','一些球员比Mazen快','कुछ खिलाड़ी माज़ेन से तेज हैं','Algunos jugadores son más rápidos que Mazen'),O('لاعب واحد فقط أسرع من خالد','Only one player is faster than Khaled','只有一名球员比Khaled快','केवल एक खिलाड़ी खालिद से तेज है','Solo un jugador es más rápido que Khaled')],2,8),
    E(L('ما أصغر عدد موجب يقبل القسمة على 4 و6 و9 دون باقٍ؟','What is the smallest positive number divisible by 4, 6, and 9?','能被4、6和9整除的最小正数是多少？','4, 6 और 9 से विभाजित होने वाली सबसे छोटी धनात्मक संख्या क्या है?','¿Cuál es el menor número positivo divisible por 4, 6 y 9?'),[O('18','18','18','18','18'),O('24','24','24','24','24'),O('36','36','36','36','36'),O('72','72','72','72','72')],2,9),
    E(L('لديك 8 كرات متشابهة وواحدة أثقل، وميزان ذو كفتين. ما أقل عدد من الوزنات المضمونة لمعرفة الكرة الأثقل؟','You have 8 identical balls and one is heavier. With a balance scale, what is the minimum guaranteed number of weighings to find it?','有8个相同球，其中一个更重。用天平保证找出重球至少需要几次称量？','8 समान गेंदों में एक भारी है。तराजू से निश्चित रूप से找出重球最少需要几次称量？','Tienes 8 bolas idénticas y una es más pesada. Con una balanza, ¿cuántas pesadas garantizan encontrarla?'),[O('1','1','1','1','1'),O('2','2','2','2','2'),O('3','3','3','3','3'),O('4','4','4','4','4')],2,10),
    E(L('إذا كانت القاعدة: كل رقم يتحول إلى ضعفه ناقص 1، فما ناتج 7؟','If the rule is double a number then subtract 1, what is the result for 7?','如果规则是数字乘2再减1，那么7的结果是多少？','यदि नियम संख्या को दोगुना करके 1 घटाना है, तो 7 का परिणाम क्या है?','Si la regla es duplicar un número y restar 1, ¿cuál es el resultado para 7?'),[O('12','12','12','12','12'),O('13','13','13','13','13'),O('14','14','14','14','14'),O('15','15','15','15','15')],1,3),
    E(L('أي كلمة تكمل العلاقة: كتاب : قراءة :: كرة : ؟','Complete the relation: Book : Reading :: Ball : ?','完成关系：书：阅读 :: 球：？','संबंध पूरा करें: किताब : पढ़ना :: गेंद : ?','Completa la relación: Libro : Leer :: Balón : ?'),[O('رمي','Throwing','投掷','फेंकना','Lanzar'),O('قراءة','Reading','阅读','पढ़ना','Leer'),O('كتابة','Writing','写作','लिखना','Escribir'),O('رسم','Drawing','绘画','चित्र बनाना','Dibujar')],0,6),
    E(L('عدد إذا ضربته في نفسه ثم أضفت إليه نفسه يساوي 30. ما العدد الموجب؟','A number multiplied by itself and then added to itself equals 30. What is the positive number?','一个数乘以自身再加上自身等于30。正数是多少？','एक संख्या को स्वयं से गुणा करके फिर उसी संख्या को जोड़ने पर 30 मिलता है। धनात्मक संख्या क्या है?','Un número multiplicado por sí mismo y luego sumado a sí mismo da 30. ¿Cuál es el número positivo?'),[O('4','4','4','4','4'),O('5','5','5','5','5'),O('6','6','6','6','6'),O('7','7','7','7','7')],1,9),
    E(L('سلسلة: 2، 6، 12، 20، 30، ؟. ما الحد التالي؟','Sequence: 2, 6, 12, 20, 30, ?. What is next?','序列：2、6、12、20、30、？下一项是什么？','श्रृंखला: 2, 6, 12, 20, 30, ?. अगला पद क्या है?','Secuencia: 2, 6, 12, 20, 30, ?. ¿Cuál es el siguiente?'),[O('40','40','40','40','40'),O('41','41','41','41','41'),O('42','42','42','42','42'),O('44','44','44','44','44')],2,10)
  );

  bank.science.questions.push(
    E(L('ما العملية التي تصنع بها النباتات غذاءها باستخدام الضوء؟','What process do plants use to make food using light?','植物利用光制造食物的过程是什么？','पौधे प्रकाश का उपयोग करके भोजन किस प्रक्रिया से बनाते हैं?','¿Qué proceso usan las plantas para fabricar alimento usando luz?'),[O('التنفس','Respiration','呼吸','श्वसन','Respiración'),O('البناء الضوئي','Photosynthesis','光合作用','प्रकाश संश्लेषण','Fotosíntesis'),O('التخمّر','Fermentation','发酵','किण्वन','Fermentación'),O('الانتشار','Diffusion','扩散','प्रसार','Difusión')],1,4),
    E(L('أي طبقة من الغلاف الجوي تحتوي معظم الأوزون؟','Which atmospheric layer contains most ozone?','大气中大部分臭氧位于哪一层？','वायुमंडल की किस परत में अधिकांश ओज़ोन होता है?','¿Qué capa de la atmósfera contiene la mayor parte del ozono?'),[O('التروبوسفير','Troposphere','对流层','क्षोभमंडल','Troposfera'),O('الستراتوسفير','Stratosphere','平流层','समतापमंडल','Estratosfera'),O('الميزوسفير','Mesosphere','中间层','मध्य मंडल','Mesosfera'),O('الإكسوسفير','Exosphere','散逸层','बहिर्मंडल','Exosfera')],1,6),
    E(L('أي نوع من الموجات لا يحتاج إلى وسط مادي لينتقل؟','Which type of wave does not require a material medium to travel?','哪种波不需要物质介质即可传播？','किस प्रकार की तरंग को यात्रा के लिए भौतिक माध्यम की आवश्यकता नहीं होती?','¿Qué tipo de onda no necesita un medio material para propagarse?'),[O('الصوت','Sound','声音','ध्वनि','Sonido'),O('الموجة المائية','Water wave','水波','जल तरंग','Onda de agua'),O('الضوء','Light','光','प्रकाश','Luz'),O('موجة الحبل','Rope wave','绳波','रस्सी की तरंग','Onda de cuerda')],2,7),
    E(L('إذا تضاعفت سرعة جسم وبقيت كتلته ثابتة، فكيف تتغير طاقته الحركية؟','If an object’s speed doubles while mass stays constant, how does its kinetic energy change?','如果物体速度加倍而质量不变，动能如何变化？','यदि वस्तु की गति दोगुनी हो और द्रव्यमान स्थिर रहे, तो गतिज ऊर्जा कैसे बदलेगी?','Si la velocidad de un objeto se duplica y la masa permanece constante, ¿cómo cambia su energía cinética?'),[O('تتضاعف','It doubles','加倍','दोगुनी','Se duplica'),O('تصبح أربعة أضعاف','It becomes four times larger','变为四倍','चार गुना हो जाती है','Se cuadruplica'),O('تبقى نفسها','It stays the same','不变','वही रहती है','Permanece igual'),O('تنخفض للنصف','It halves','减半','आधी हो जाती है','Se reduce a la mitad')],1,9),
    E(L('ما عدد الكروموسومات في الخلية الجسدية البشرية الطبيعية؟','How many chromosomes are in a normal human somatic cell?','正常人类体细胞有多少条染色体？','सामान्य मानव सोमैटिक कोशिका में कितने गुणसूत्र होते हैं?','¿Cuántos cromosomas hay en una célula somática humana normal?'),[O('23','23','23','23','23'),O('46','46','46','46','46'),O('44','44','44','44','44'),O('48','48','48','48','48')],1,8),
    E(L('أي مقياس يستخدم لقياس الحموضة والقاعدية؟','Which scale measures acidity and basicity?','哪个尺度用于测量酸碱度？','अम्लता और क्षारीयता को कौन सा पैमाना मापता है?','¿Qué escala mide la acidez y basicidad?'),[O('pH','pH','pH','pH','pH'),O('ديسيبل','Decibel','分贝','डेसीबल','Decibel'),O('كلفن','Kelvin','开尔文','केल्विन','Kelvin'),O('واط','Watt','瓦特','वाट','Vatio')],0,5),
    E(L('ما القوة التي تجذب الأجسام نحو مركز الأرض؟','What force attracts objects toward Earth’s center?','什么力把物体吸向地球中心？','कौन सा बल वस्तुओं को पृथ्वी के केंद्र की ओर खींचता है?','¿Qué fuerza atrae los objetos hacia el centro de la Tierra?'),[O('الاحتكاك','Friction','摩擦力','घर्षण','Fricción'),O('المغناطيسية','Magnetism','磁力','चुंबकत्व','Magnetismo'),O('الجاذبية','Gravity','引力','गुरुत्वाकर्षण','Gravedad'),O('الطفو','Buoyancy','浮力','उत्प्लावन','Flotación')],2,3),
    E(L('أي قاعدة تصف أن لكل فعل قوة مساوية له في المقدار ومعاكسة في الاتجاه؟','Which law states that every action has an equal and opposite reaction?','哪条定律说明每个作用力都有大小相等、方向相反的反作用力？','कौन सा नियम कहता है कि हर क्रिया की समान और विपरीत प्रतिक्रिया होती है?','¿Qué ley establece que a toda acción corresponde una reacción igual y opuesta?'),[O('قانون نيوتن الأول','Newton’s First Law','牛顿第一定律','न्यूटन का प्रथम नियम','Primera ley de Newton'),O('قانون نيوتن الثاني','Newton’s Second Law','牛顿第二定律','न्यूटन का दूसरा नियम','Segunda ley de Newton'),O('قانون نيوتن الثالث','Newton’s Third Law','牛顿第三定律','न्यूटन का तीसरा नियम','Tercera ley de Newton'),O('قانون حفظ الكتلة','Conservation of mass','质量守恒定律','द्रव्यमान संरक्षण','Conservación de la masa')],2,10),
    E(L('إذا كان الرقم الهيدروجيني 3، فالمحلول حمضي أم قاعدي؟','If the pH is 3, is the solution acidic or basic?','如果pH为3，溶液是酸性还是碱性？','यदि pH 3 है, तो विलयन अम्लीय है या क्षारीय?','Si el pH es 3, ¿la solución es ácida o básica?'),[O('قاعدي','Basic','碱性','क्षारीय','Básica'),O('متعادل','Neutral','中性','तटस्थ','Neutra'),O('حمضي','Acidic','酸性','अम्लीय','Ácida'),O('لا يمكن معرفة ذلك','Cannot tell','无法判断','पता नहीं चल सकता','No se puede saber')],2,6),
    E(L('ما العامل الذي يحدد لون الضوء المرئي فيزيائيًا؟','What physical property determines the color of visible light?','从物理上看，什么性质决定可见光的颜色？','भौतिक रूप से दृश्य प्रकाश का रंग किस गुण से निर्धारित होता है?','¿Qué propiedad física determina el color de la luz visible?'),[O('التردد','Frequency','频率','आवृत्ति','Frecuencia'),O('الكتلة','Mass','质量','द्रव्यमान','Masa'),O('الزمن','Time','时间','समय','Tiempo'),O('الكثافة دائمًا','Density always','总是密度','हमेशा घनत्व','Densidad siempre')],0,10)
  );

  bank.daily.questions.push(
    E(L('ما العدد الذي إذا أضفت إليه 18 يصبح 50؟','What number becomes 50 when 18 is added to it?','哪个数加18等于50？','किस संख्या में 18 जोड़ने पर 50 मिलता है?','¿Qué número se convierte en 50 al sumarle 18?'),[O('22','22','22','22','22'),O('28','28','28','28','28'),O('32','32','32','32','32'),O('38','38','38','38','38')],2,3),
    E(L('إذا كان كل مربع مستطيلاً، فهل كل مستطيل مربع؟','If every square is a rectangle, is every rectangle a square?','如果每个正方形都是矩形，那么每个矩形都是正方形吗？','यदि हर वर्ग एक आयत है, तो क्या हर आयत वर्ग है?','Si todo cuadrado es un rectángulo, ¿todo rectángulo es un cuadrado?'),[O('نعم دائمًا','Yes, always','是的，总是','हाँ, हमेशा','Sí, siempre'),O('لا','No','不是','नहीं','No'),O('فقط الدائرة','Only circles','只有圆','केवल वृत्त','Solo círculos'),O('لا يمكن المقارنة','Cannot compare','无法比较','तुलना नहीं की जा सकती','No se puede comparar')],1,5),
    E(L('ما ناتج 9 × 7؟','What is 9 × 7?','9 × 7 等于多少？','9 × 7 कितना है?','¿Cuánto es 9 × 7?'),[O('56','56','56','56','56'),O('63','63','63','63','63'),O('72','72','72','72','72'),O('81','81','81','81','81')],1,2),
    E(L('إذا تحركت 3 خطوات شمالًا ثم 3 شرقًا، فأين تكون بالنسبة لنقطة البداية؟','If you move 3 steps north then 3 east, where are you relative to the start?','向北走3步再向东走3步，你相对起点在哪里？','यदि आप 3 कदम उत्तर और फिर 3 कदम पूर्व चलते हैं, तो शुरुआत के सापेक्ष कहाँ होंगे?','Si avanzas 3 pasos al norte y luego 3 al este, ¿dónde estás respecto al inicio?'),[O('شمال شرق','Northeast','东北','उत्तर-पूर्व','Noreste'),O('شمال غرب','Northwest','西北','उत्तर-पश्चिम','Noroeste'),O('جنوب شرق','Southeast','东南','दक्षिण-पूर्व','Sureste'),O('جنوب غرب','Southwest','西南','दक्षिण-पश्चिम','Suroeste')],0,4),
    E(L('ما العدد المفقود: 4، 9، 14، 19، ؟','What is missing: 4, 9, 14, 19, ?','缺少的数字是什么：4、9、14、19、？','लुप्त संख्या क्या है: 4, 9, 14, 19, ?','¿Qué falta: 4, 9, 14, 19, ?'),[O('22','22','22','22','22'),O('23','23','23','23','23'),O('24','24','24','24','24'),O('25','25','25','25','25')],2,5),
    E(L('إذا كان لديك 120 دينارًا وأنفقت 25% منها، كم بقي؟','If you have 120 dinars and spend 25%, how much remains?','你有120第纳尔，花掉25%后还剩多少？','यदि आपके पास 120 दीनार हैं और आप 25% खर्च करते हैं, तो कितना बचा?','Si tienes 120 dinares y gastas el 25%, ¿cuánto queda?'),[O('80','80','80','80','80'),O('90','90','90','90','90'),O('95','95','95','95','95'),O('100','100','100','100','100')],1,7),
    E(L('أي ترتيب يطابق القاعدة: أحمر قبل أزرق، وأخضر بعد أزرق؟','Which order follows the rule: red before blue, and green after blue?','哪个顺序符合规则：红色在蓝色前，绿色在蓝色后？','कौन सा क्रम नियम का पालन करता है: लाल नीले से पहले और हरा नीले के बाद?','¿Qué orden cumple: rojo antes de azul y verde después de azul?'),[O('أزرق، أحمر، أخضر','Blue, Red, Green','蓝、红、绿','नीला, लाल, हरा','Azul, Rojo, Verde'),O('أحمر، أزرق، أخضر','Red, Blue, Green','红、蓝、绿','लाल, नीला, हरा','Rojo, Azul, Verde'),O('أخضر، أزرق، أحمر','Green, Blue, Red','绿、蓝、红','हरा, नीला, लाल','Verde, Azul, Rojo'),O('أزرق، أخضر، أحمر','Blue, Green, Red','蓝、绿、红','नीला, हरा, लाल','Azul, Verde, Rojo')],1,6),
    E(L('إذا كان متوسط 4 أعداد هو 18، فما مجموعها؟','If the average of 4 numbers is 18, what is their sum?','4个数的平均值是18，它们的和是多少？','4 संख्याओं का औसत 18 है। उनका योग कितना है?','Si el promedio de 4 números es 18, ¿cuál es su suma?'),[O('54','54','54','54','54'),O('64','64','64','64','64'),O('72','72','72','72','72'),O('82','82','82','82','82')],2,8),
    E(L('لديك 5 صناديق، في كل صندوق 8 كرات، وأخرجت 7 كرات. كم بقي؟','You have 5 boxes with 8 balls each, and remove 7 balls. How many remain?','你有5个箱子，每个8个球，取出7个后剩多少？','5 डिब्बों में प्रत्येक में 8 गेंदें हैं, 7 निकाल दीं। कितनी बचीं?','Tienes 5 cajas con 8 pelotas cada una y retiras 7. ¿Cuántas quedan?'),[O('31','31','31','31','31'),O('33','33','33','33','33'),O('34','34','34','34','34'),O('35','35','35','35','35')],2,7)
,
E(L('ما العدد الذي يساوي ثلاثة أرباع 80؟','What number is three quarters of 80?','80的四分之三是多少？','80 का तीन-चौथाई कितना है?','¿Qué número es tres cuartos de 80?'),[O('40','40','40','40','40'),O('50','50','50','50','50'),O('60','60','60','60','60'),O('70','70','70','70','70')],2,9),
  );

  bank.horror.questions.push(
    E(L('ينطفئ الصوت تمامًا لثلاث ثوانٍ. ما أفضل استجابة؟','The sound disappears completely for three seconds. What is the best response?','声音完全消失三秒。最好的反应是什么？','आवाज़ तीन सेकंड के लिए पूरी तरह गायब हो जाती है। सबसे अच्छा जवाब क्या है?','El sonido desaparece por tres segundos. ¿Cuál es la mejor respuesta?'),[O('أتصرف فورًا','Act immediately','立即行动','तुरंत कार्रवाई','Actuar de inmediato'),O('أراقب وأتحقق قبل القرار','Observe and verify before deciding','观察并核实后再决定','निर्णय से पहले देखना और जाँचना','Observar y verificar antes de decidir'),O('أغلق عيني','Close my eyes','闭上眼睛','आँखें बंद करना','Cerrar los ojos'),O('أضغط كل الأزرار','Press every button','按下所有按钮','सभी बटन दबाना','Pulsar todos los botones')],1,4),
    E(L('تظهر أمامك رسالة: «أنت تراقب الباب الخطأ». ماذا تفعل؟','A message appears: “You are watching the wrong door.” What do you do?','出现一条信息：“你正在观察错误的门。”你怎么办？','संदेश आता है: “तुम गलत दरवाज़े को देख रहे हो।” क्या करेंगे?','Aparece un mensaje: “Estás vigilando la puerta equivocada”. ¿Qué haces?'),[O('أصدقها فورًا','Believe it immediately','立即相信','तुरंत विश्वास','Creerlo de inmediato'),O('أبحث عن دليل آخر','Look for another clue','寻找其他线索','दूसरा सुराग ढूँढना','Buscar otra pista'),O('أهرب','Run away','逃跑','भाग जाना','Huir'),O('أطفئ الشاشة','Turn off the screen','关闭屏幕','स्क्रीन बंद करना','Apagar la pantalla')],1,6),
    E(L('الحارس يعرض خيارين متطابقين بصريًا. ما أول مهارة تستخدمها؟','The warden shows two visually identical choices. What skill do you use first?','守卫给出两个视觉上完全相同的选项。首先使用什么能力？','गार्ड दो बिल्कुल समान दिखने वाले विकल्प देता है। पहले कौन सा कौशल इस्तेमाल करेंगे?','El guardián muestra dos opciones visualmente idénticas. ¿Qué habilidad usas primero?'),[O('السرعة','Speed','速度','गति','Velocidad'),O('فحص التفاصيل','Inspect details','检查细节','विवरण जाँचना','Revisar detalles'),O('الحظ','Luck','运气','भाग्य','Suerte'),O('التخمين','Guessing','猜测','अनुमान','Adivinar')],1,7),
    E(L('تجد ثلاث رسائل: الأولى تكذب دائمًا، الثانية تقول الحقيقة دائمًا، والثالثة عشوائية. ما أفضل منهج؟','You find three messages: the first always lies, the second always tells the truth, and the third is random. What is the best approach?','你发现三条信息：第一条总是撒谎，第二条总是真话，第三条随机。最佳方法是什么？','आपको तीन संदेश मिलते हैं: पहला हमेशा झूठ बोलता है, दूसरा हमेशा सच कहता है, तीसरा यादृच्छिक है। सबसे अच्छा तरीका क्या है?','Encuentras tres mensajes: el primero siempre miente, el segundo siempre dice la verdad y el tercero es aleatorio. ¿Cuál es el mejor enfoque?'),[O('اختيار عشوائي','Choose randomly','随机选择','यादृच्छिक चुनना','Elegir al azar'),O('البحث عن معلومة يمكن التحقق منها بشكل مستقل','Find independently verifiable information','寻找可独立验证的信息','स्वतंत्र रूप से सत्यापित जानकारी ढूँढना','Buscar información verificable de forma independiente'),O('اتباع الرسالة الأولى','Follow the first message','遵循第一条','पहले संदेश का पालन','Seguir el primero'),O('اتباع الرسالة الثالثة','Follow the third message','遵循第三条','तीसरे संदेश का पालन','Seguir el tercero')],1,9),
    E(L('الحارس يقول: «إذا عرفتني فلن تحتاج إلى رؤيتي». ما الذي ينبغي أن تفترضه؟','The warden says: “If you know me, you will not need to see me.” What should you assume?','守卫说：“如果你了解我，就不需要看见我。”你应该假设什么？','गार्ड कहता है: “अगर तुम मुझे जानते हो तो तुम्हें मुझे देखने की जरूरत नहीं होगी।” क्या मानना चाहिए?','El guardián dice: “Si me conoces, no necesitarás verme”. ¿Qué deberías asumir?'),[O('أن العبارة دليل كافٍ','The statement is enough evidence','这句话本身就是充分证据','यह कथन पर्याप्त प्रमाण है','La frase es evidencia suficiente'),O('أنها محاولة للتأثير على قرارك','It may be trying to influence your decision','这可能是在影响你的决定','यह आपके निर्णय को प्रभावित करने की कोशिश हो सकती है','Puede ser un intento de influir en tu decisión'),O('أن الحارس صديقك','The warden is your friend','守卫是你的朋友','गार्ड आपका दोस्त है','El guardián es tu amigo'),O('أن الباب مفتوح','The door is open','门是开的','दरवाज़ा खुला है','La puerta está abierta')],1,10),
    E(L('تسمع نبضًا يطابق إيقاعك. هل يعني ذلك أن هناك شخصًا آخر؟','You hear a pulse matching your rhythm. Does that mean someone else is there?','你听到与自己节奏一致的脉搏声。这意味着还有别人吗？','आपको अपनी लय से मेल खाती धड़कन सुनाई देती है। क्या इसका मतलब कोई और है?','Oyes un pulso que coincide con tu ritmo. ¿Significa que hay otra persona?'),[O('نعم بالتأكيد','Yes, definitely','是的，肯定','हाँ, निश्चित रूप से','Sí, definitivamente'),O('لا يمكن الاستنتاج من الصوت وحده','It cannot be concluded from sound alone','仅凭声音无法得出结论','केवल आवाज़ से निष्कर्ष नहीं निकाला जा सकता','No puede concluirse solo por el sonido'),O('الحارس موجود دائمًا','The warden is always there','守卫一直在','गार्ड हमेशा वहाँ है','El guardián siempre está allí'),O('هذا يعني أن اللعبة انتهت','It means the game is over','这意味着游戏结束','इसका मतलब खेल खत्म है','Significa que el juego terminó')],1,5),
    E(L('الباب يفتح عندما تتوقف عن محاولة فتحه. ماذا تستنتج؟','The door opens when you stop trying to open it. What do you infer?','当你停止尝试开门时，门反而打开了。你推断什么？','दरवाज़ा तब खुलता है जब आप उसे खोलने की कोशिश बंद कर देते हैं। क्या निष्कर्ष है?','La puerta se abre cuando dejas de intentar abrirla. ¿Qué infieres?'),[O('المحاولة نفسها كانت جزءًا من اللغز','The attempt itself was part of the puzzle','尝试本身就是谜题的一部分','प्रयास स्वयं पहेली का हिस्सा था','El intento era parte del acertijo'),O('الباب مكسور','The door is broken','门坏了','दरवाज़ा टूटा है','La puerta está rota'),O('الحارس فتحه يقينًا','The warden definitely opened it','守卫肯定打开了','गार्ड ने निश्चित रूप से खोला','El guardián lo abrió'),O('لا معنى لذلك','It means nothing','没有意义','इसका कोई अर्थ नहीं','No significa nada')],0,8),
    E(L('آخر سؤال يكرر نمطًا رأيته سابقًا، لكن أحد التفاصيل تغيّر. ما أهم شيء؟','The final question repeats a pattern you saw earlier, but one detail changed. What matters most?','最后一道题重复了之前见过的模式，但有一个细节改变了。最重要的是什么？','अंतिम प्रश्न पहले देखे गए पैटर्न को दोहराता है, लेकिन एक विवरण बदल गया है। सबसे महत्वपूर्ण क्या है?','La última pregunta repite un patrón anterior, pero un detalle cambió. ¿Qué importa más?'),[O('الاعتماد على الذاكرة فقط','Rely only on memory','只依赖记忆','केवल स्मृति पर निर्भर होना','Depender solo de la memoria'),O('ملاحظة التفاصيل الجديدة','Notice the new detail','注意新的细节','नए विवरण पर ध्यान देना','Notar el nuevo detalle'),O('الإجابة بأسرع وقت','Answer as fast as possible','尽快回答','जितनी जल्दी हो सके जवाब देना','Responder lo más rápido posible'),O('اختيار نفس الإجابة السابقة','Choose the previous answer','选择之前的答案','पिछला उत्तर चुनना','Elegir la respuesta anterior')],1,10),
    E(L('إذا أعطاك الحارس معلومة صحيحة لكنها غير مرتبطة بالسؤال، هل تساعدك؟','If the warden gives you a true fact unrelated to the question, does it help?','如果守卫给出一个真实但与问题无关的事实，它有帮助吗？','यदि गार्ड आपको एक सही लेकिन सवाल से असंबंधित तथ्य देता है, तो क्या वह मदद करता है?','Si el guardián te da un dato verdadero pero no relacionado con la pregunta, ¿te ayuda?'),[O('نعم دائمًا','Yes, always','是的，总是','हाँ, हमेशा','Sí, siempre'),O('ليس بالضرورة','Not necessarily','不一定','ज़रूरी नहीं','No necesariamente'),O('يضمن الإجابة','It guarantees the answer','它保证答案','यह उत्तर की गारंटी देता है','Garantiza la respuesta'),O('يلغي السؤال','It cancels the question','它取消问题','यह सवाल रद्द करता है','Cancela la pregunta')],1,6),

    E(L('يظهر خيار ثالث لم يكن موجودًا من قبل. ما أول سؤال تسأله لنفسك؟','A third option appears that was not there before. What is the first question you ask yourself?','出现了一个之前不存在的第三个选项。你首先问自己什么？','एक तीसरा विकल्प दिखाई देता है जो पहले नहीं था। आप खुद से पहला सवाल क्या पूछेंगे?','Aparece una tercera opción que antes no existía. ¿Cuál es la primera pregunta que te haces?'),[O('لماذا تغيّر المشهد؟','Why did the scene change?','为什么场景改变了？','दृश्य क्यों बदला?','¿Por qué cambió la escena?'),O('أي خيار يبدو أجمل؟','Which option looks nicer?','哪个选项看起来更好？','कौन सा विकल्प बेहतर दिखता है?','¿Qué opción se ve mejor?'),O('هل أستطيع الضغط بسرعة؟','Can I press quickly?','我能快速按下吗？','क्या मैं जल्दी दबा सकता हूँ?','¿Puedo pulsar rápido?'),O('هل الحارس يتوقع مني التفكير؟','Does the warden expect me to think?','守卫是否希望我思考？','क्या गार्ड चाहता है कि मैं सोचूँ?','¿Espera el guardián que piense?')],0,8),

  );

  // New sports challenge: preserves ZIVOZONE's sports identity and adds a
  // competitive path without changing the existing challenge IDs.
  bank.football={id:'football',icon:'⚽',xp:90,title:A('تحدي كرة القدم','Football Challenge','足球挑战','फुटबॉल चैलेंज','Desafío de fútbol'),desc:A('10 أسئلة كروية من الأساسيات إلى التفكير التكتيكي.','10 football questions from basics to tactical thinking.','10道足球题，从基础到战术思维。','10 फुटबॉल प्रश्न, बुनियादी से सामरिक सोच तक।','10 preguntas de fútbol, de fundamentos a pensamiento táctico.'),questions:[
    E(L('كم لاعبًا يبدأ به الفريق في الملعب في كرة القدم؟','How many players start on the field for one football team?','一支足球队在场上开始比赛时有多少名球员？','एक फुटबॉल टीम मैदान पर कितने खिलाड़ियों से शुरू करती है?','¿Con cuántos jugadores comienza un equipo de fútbol en el campo?'),[O('9','9','9','9','9'),O('10','10','10','10','10'),O('11','11','11','11','11'),O('12','12','12','12','12')],2,1),
    E(L('ما الهدف الأساسي من الضغط العالي؟','What is a main objective of high pressing?','高位压迫的主要目标是什么？','हाई प्रेसिंग का मुख्य उद्देश्य क्या है?','¿Cuál es un objetivo principal de la presión alta?'),[O('منح الخصم وقتًا أكبر','Give the opponent more time','给对手更多时间','विरोधी को अधिक समय देना','Dar más tiempo al rival'),O('استعادة الكرة قريبًا من مرمى الخصم','Win the ball back near the opponent goal','在对方球门附近夺回球权','प्रतिद्वंद्वी के गोल के पास गेंद वापस पाना','Recuperar el balón cerca de la portería rival'),O('إبطاء المباراة فقط','Only slow the game','只减慢比赛','केवल खेल धीमा करना','Solo ralentizar el juego'),O('إبعاد الحارس عن المرمى','Move the goalkeeper away','让门将离开球门','गोलकीपर को गोल से दूर करना','Alejar al portero')],1,4),
    E(L('في 4-3-3، ما فائدة عرض الملعب بالجناحين؟','In a 4-3-3, what is a benefit of using wingers to provide width?','在4-3-3中，边锋提供宽度有什么好处？','4-3-3 में विंगरों द्वारा चौड़ाई देने का क्या लाभ है?','En un 4-3-3, ¿qué beneficio tiene dar amplitud con los extremos?'),[O('تضييق الملعب','Narrow the field','缩小场地','मैदान संकरा करना','Estrechar el campo'),O('سحب الخط الدفاعي وفتح مساحات داخلية','Stretch the defense and open central spaces','拉开防线并打开中路空间','रक्षा को फैलाकर अंदर जगह खोलना','Estirar la defensa y abrir espacios interiores'),O('منع التمرير دائمًا','Always stop passing','始终阻止传球','हमेशा पास रोकना','Impedir siempre el pase'),O('إلغاء دور الوسط','Remove midfield roles','取消中场作用','मिडफील्ड की भूमिका हटाना','Eliminar el medio campo')],1,6),
    E(L('إذا كان الخصم يضغط رجلًا لرجل، ما الحل الشائع لبناء اللعب؟','If the opponent uses man-to-man pressing, what is a common build-up solution?','如果对手采用人盯人压迫，常见的组织进攻解决方案是什么？','यदि विरोधी मैन-टू-मैन प्रेसिंग करता है, तो बिल्ड-अप का सामान्य समाधान क्या है?','Si el rival presiona hombre a hombre, ¿cuál es una solución común para iniciar el juego?'),[O('تجميد جميع اللاعبين','Freeze all players','让所有球员站住','सभी खिलाड़ियों को स्थिर करना','Congelar a todos'),O('خلق لاعب حر بالحركة وتبادل المراكز','Create a free player through movement and rotations','通过移动和换位创造自由球员','आंदोलन और रोटेशन से फ्री खिलाड़ी बनाना','Crear un jugador libre mediante movimientos y rotaciones'),O('اللعب الطويل دائمًا','Always play long','总是长传','हमेशा लंबी गेंद खेलना','Jugar siempre en largo'),O('إخراج الكرة خارج الملعب','Put the ball out','把球踢出界','गेंद बाहर करना','Sacar el balón fuera')],1,8),
    E(L('عندما يخسر الفريق الكرة، ما أول مبدأ في التحول الدفاعي؟','When a team loses the ball, what is a first defensive transition principle?','球队丢球后，防守转换的首要原则是什么？','टीम के गेंद खोने पर डिफेंसिव ट्रांज़िशन का पहला सिद्धांत क्या है?','Cuando un equipo pierde el balón, ¿cuál es un primer principio de transición defensiva?'),[O('الاستسلام','Give up','放弃','हार मानना','Rendirse'),O('الرد الفوري وتنظيم المسافات','React immediately and organize distances','立即反应并组织间距','तुरंत प्रतिक्रिया और दूरी व्यवस्थित करना','Reaccionar de inmediato y organizar distancias'),O('كل لاعب يركض وحده','Everyone runs alone','每人单独跑','हर खिलाड़ी अकेले दौड़े','Cada jugador corre solo'),O('الاحتفال','Celebrate','庆祝','जश्न मनाना','Celebrar')],1,7),
    E(L('ما فائدة التمرير الثالث في بعض أنماط اللعب؟','What is the benefit of a third-man pass in some playing patterns?','在一些进攻模式中，第三人传球有什么好处？','कुछ खेल पैटर्न में थर्ड-मैन पास का क्या लाभ है?','¿Qué beneficio tiene el pase del tercer hombre en algunos patrones de juego?'),[O('خلق لاعب ثالث حر خلف الضغط','Free a third player beyond the pressure','让第三名球员在压迫后方获得自由','दबाव के पीछे तीसरे खिलाड़ी को मुक्त करना','Liberar a un tercer jugador detrás de la presión'),O('إيقاف اللعب','Stop play','停止比赛','खेल रोकना','Detener el juego'),O('تقليل عدد اللاعبين','Reduce players','减少球员','खिलाड़ियों को कम करना','Reducir jugadores'),O('منع التحرك','Prevent movement','阻止移动','आंदोलन रोकना','Impedir movimiento')],0,9),
    E(L('إذا كان الجناح يستلم بين الظهير وقلب الدفاع، فما نوع المساحة التي يستغلها غالبًا؟','If a winger receives between the fullback and center-back, what space is often exploited?','如果边锋在边后卫和中后卫之间接球，他通常利用什么空间？','यदि विंगर फुलबैक और सेंटर-बैक के बीच गेंद लेता है, तो वह किस जगह का उपयोग करता है?','Si un extremo recibe entre lateral y central, ¿qué espacio suele explotar?'),[O('الممر النصفي','Half-space','肋部空间','हाफ-स्पेस','Pasillo interior'),O('خلف المرمى','Behind the goal','球门后方','गोल के पीछे','Detrás de la portería'),O('دائرة المنتصف فقط','Only center circle','只有中圈','केवल सेंटर सर्कल','Solo el círculo central'),O('خارج الملعب','Outside the field','场外','मैदान के बाहर','Fuera del campo')],0,7),
    E(L('فريقك يتقدم 1-0 في الدقائق الأخيرة. ما القرار التكتيكي الأفضل عمومًا؟','Your team leads 1-0 late in the game. What is generally the best tactical decision?','球队在最后阶段1-0领先。一般来说最佳战术决定是什么？','आपकी टीम मैच के अंतिम मिनटों में 1-0 आगे है। सामान्यतः बेहतर सामरिक निर्णय क्या है?','Tu equipo gana 1-0 en los últimos minutos. ¿Cuál suele ser la mejor decisión táctica?'),[O('المخاطرة بلا داعٍ','Take unnecessary risks','进行不必要的冒险','अनावश्यक जोखिम लेना','Asumir riesgos innecesarios'),O('إدارة المخاطر مع الحفاظ على التهديد الهجومي','Manage risk while retaining an attacking threat','控制风险同时保持进攻威胁','जोखिम नियंत्रित करते हुए आक्रमण की धमकी बनाए रखना','Gestionar el riesgo manteniendo amenaza ofensiva'),O('إيقاف كل تحرك','Stop all movement','停止所有移动','सभी गतिविधि रोकना','Detener todo movimiento'),O('إخراج أفضل لاعب فورًا دائمًا','Always remove the best player','总是立即换下最佳球员','हमेशा सर्वश्रेष्ठ खिलाड़ी को तुरंत替换','Sacar siempre al mejor jugador')],1,9),
    E(L('ما الذي يجعل التحدي التكتيكي عالي الجودة؟','What makes a tactical challenge high quality?','什么让战术挑战具有高质量？','एक सामरिक चुनौती को उच्च गुणवत्ता वाला क्या बनाता है?','¿Qué hace que un desafío táctico sea de alta calidad?'),[O('حفظ أسماء فقط','Only memorizing names','只记名字','केवल नाम याद करना','Solo memorizar nombres'),O('اختيار قرار وربطه بالسياق والمساحات والمخاطر','Linking a decision to context, spaces and risks','把决策与情境、空间和风险联系起来','निर्णय को संदर्भ, स्थान और जोखिम से जोड़ना','Relacionar una decisión con contexto, espacios y riesgos'),O('الإجابة العشوائية','Random answers','随机回答','respuestas al azar','Respuestas al azar'),O('تجاهل الخصم','Ignore the opponent','忽略对手','प्रतिद्वंद्वी को नजरअंदाज करना','Ignorar al rival')],1,10)
,
    E(L('متى يكون التمرير إلى الخلف قرارًا جيدًا؟','When can a backward pass be a good decision?','什么时候向后传球是一个好决定？','पीछे की ओर पास कब अच्छा निर्णय हो सकता है?','¿Cuándo puede ser buena decisión un pase hacia atrás?'),[O('عندما يحافظ على الاستحواذ ويعيد تنظيم الفريق','When it keeps possession and reorganizes the team','当它保持控球并重新组织球队','जब इससे कब्ज़ा बना रहे और टीम फिर से संगठित हो','Cuando conserva la posesión y reorganiza al equipo'),O('دائمًا لأنه آمن','Always because it is safe','总是因为安全','हमेशा क्योंकि यह सुरक्षित है','Siempre porque es seguro'),O('عندما لا يوجد لاعب آخر','When there is no other player','当没有其他球员时','जब कोई और खिलाड़ी न हो','Cuando no hay otro jugador'),O('لا يكون جيدًا أبدًا','It is never good','从来都不好','कभी अच्छा नहीं','Nunca es bueno')],0,5)
  ]};

  // Assign stable IDs after all pools are assembled.
  Object.values(bank).forEach(ch=>{if(ch?.questions)ch.questions.forEach((q,i)=>{q.id=q.id||`${ch.id}_${i+1}`})});

  window.ZIVOZONE_CHALLENGES=bank;
  window.ZIVOZONE_CHALLENGES.get=id=>bank[id]||null;
  window.ZIVOZONE_CHALLENGES.getAll=()=>Object.values(bank).filter(x=>x&&!x.special);
})();
