from pathlib import Path
p=Path('/mnt/data/zivo_next22/core/modules/runtime/i18n.js')
s=p.read_text(encoding='utf8')
marker="  function tr(key,lang=get()){"
keys={
'ar':"achievementSystem:'نظام الإنجازات',achievementsTitle:'إنجازات اللاعب',achievementLevel:'المستوى',achievementShare:'شارك بطاقة اللاعب',achievementCopied:'تم نسخ بطاقة اللاعب للمشاركة',achievementFirstStep:'أول تحدي',achievementSpeed:'أجبت قبل انتهاء الوقت',achievementTenGames:'10 ألعاب مكتملة',achievementPerfect:'نتيجة كاملة في تحدٍ',achievementStreak:'بنيت سلسلة لعب',achievementVeteran:'25 لعبة مكتملة',achievementDark:'دخلت الغرفة المظلمة',competitionSeason:'ساحة المنافسة',competitionSubtitle:'العودة كل يوم تصنع الفارق.',streak:'السلسلة',continuousDays:'يوم متواصل',xpReward:'مكافأة XP',whenCompleteToday:'عند إكمال اليوم',zivoReward:'مكافأة ZIVO',dailyReward:'مكافأة اليوم',weekProgress:'هذا الأسبوع',competitionClaim:'استلام مكافأة اليوم',competitionClaimed:'تم استلام مكافأة اليوم ✓',competitionComplete:'أكمل اليوم ثم استلم مكافأتك.',competitionStart:'ابدأ من تحدي اليوم لبناء السلسلة.',playerMissions:'مهام اللاعب',todayMissions:'مهام اليوم',missionsSubtitle:'أنجزها وارفع مستواك',missionsDescription:'المهام اليومية تضيف أهدافًا قصيرة حتى يكون لكل دخول سبب جديد للعب.',missionPlay:'أكمل تحديًا',missionCorrect:'أجب 5 إجابات صحيحة',missionSpeed:'أجب بسرعة',claim:'استلم'},
'en':"achievementSystem:'ACHIEVEMENT SYSTEM',achievementsTitle:'Player Achievements',achievementLevel:'Level',achievementShare:'Share player card',achievementCopied:'Player card copied for sharing',achievementFirstStep:'First challenge',achievementSpeed:'Answered before time ran out',achievementTenGames:'10 completed games',achievementPerfect:'Perfect challenge score',achievementStreak:'Built a play streak',achievementVeteran:'25 completed games',achievementDark:'Entered the Dark Room',competitionSeason:'Competition Arena',competitionSubtitle:'Come back every day to build momentum.',streak:'Streak',continuousDays:'consecutive days',xpReward:'XP REWARD',whenCompleteToday:'When you complete today',zivoReward:'ZIVO REWARD',dailyReward:'Daily reward',weekProgress:'this week',competitionClaim:'Claim today’s reward',competitionClaimed:'Today’s reward claimed ✓',competitionComplete:'Complete today, then claim your reward.',competitionStart:'Start today’s challenge to build your streak.',playerMissions:'PLAYER MISSIONS',todayMissions:'Today’s Missions',missionsSubtitle:'Complete them and level up',missionsDescription:'Daily missions add short goals so every visit has a new reason to play.',missionPlay:'Complete a challenge',missionCorrect:'Get 5 correct answers',missionSpeed:'Answer quickly',claim:'Claim'",
'zh':"achievementSystem:'成就系统',achievementsTitle:'玩家成就',achievementLevel:'等级',achievementShare:'分享玩家卡片',achievementCopied:'玩家卡片已复制',achievementFirstStep:'完成首次挑战',achievementSpeed:'在时间结束前作答',achievementTenGames:'完成10场游戏',achievementPerfect:'挑战获得满分',achievementStreak:'建立连续游戏记录',achievementVeteran:'完成25场游戏',achievementDark:'进入黑暗房间',competitionSeason:'竞技场',competitionSubtitle:'每天回来，持续进步。',streak:'连续记录',continuousDays:'连续天数',xpReward:'XP 奖励',whenCompleteToday:'完成今日任务后',zivoReward:'ZIVO 奖励',dailyReward:'每日奖励',weekProgress:'本周',competitionClaim:'领取今日奖励',competitionClaimed:'今日奖励已领取 ✓',competitionComplete:'完成今日任务后即可领取奖励。',competitionStart:'开始今日挑战，建立连续记录。',playerMissions:'玩家任务',todayMissions:'今日任务',missionsSubtitle:'完成任务并升级',missionsDescription:'每日任务提供短目标，让每次进入都有新的玩法。',missionPlay:'完成一次挑战',missionCorrect:'答对5题',missionSpeed:'快速作答',claim:'领取'",
'hi':"achievementSystem:'उपलब्धि प्रणाली',achievementsTitle:'खिलाड़ी उपलब्धियाँ',achievementLevel:'स्तर',achievementShare:'खिलाड़ी कार्ड साझा करें',achievementCopied:'खिलाड़ी कार्ड कॉपी हो गया',achievementFirstStep:'पहली चुनौती',achievementSpeed:'समय समाप्त होने से पहले उत्तर',achievementTenGames:'10 खेल पूरे',achievementPerfect:'चुनौती में पूर्ण स्कोर',achievementStreak:'लगातार खेलने की श्रृंखला',achievementVeteran:'25 खेल पूरे',achievementDark:'डार्क रूम में प्रवेश',competitionSeason:'प्रतियोगिता क्षेत्र',competitionSubtitle:'हर दिन लौटें और आगे बढ़ें।',streak:'स्ट्रीक',continuousDays:'लगातार दिन',xpReward:'XP पुरस्कार',whenCompleteToday:'आज पूरा करने पर',zivoReward:'ZIVO पुरस्कार',dailyReward:'दैनिक पुरस्कार',weekProgress:'इस सप्ताह',competitionClaim:'आज का पुरस्कार लें',competitionClaimed:'आज का पुरस्कार लिया गया ✓',competitionComplete:'आज पूरा करें और फिर पुरस्कार लें।',competitionStart:'स्ट्रीक बनाने के लिए आज की चुनौती शुरू करें।',playerMissions:'खिलाड़ी मिशन',todayMissions:'आज के मिशन',missionsSubtitle:'पूरा करें और स्तर बढ़ाएँ',missionsDescription:'दैनिक मिशन छोटे लक्ष्य देते हैं ताकि हर विज़िट में खेलने का नया कारण हो।',missionPlay:'एक चुनौती पूरी करें',missionCorrect:'5 सही उत्तर दें',missionSpeed:'तेज़ उत्तर दें',claim:'लें'",
'es':"achievementSystem:'SISTEMA DE LOGROS',achievementsTitle:'Logros del jugador',achievementLevel:'Nivel',achievementShare:'Compartir tarjeta del jugador',achievementCopied:'Tarjeta del jugador copiada',achievementFirstStep:'Primer desafío',achievementSpeed:'Respondió antes de que acabara el tiempo',achievementTenGames:'10 partidas completadas',achievementPerfect:'Puntuación perfecta en un desafío',achievementStreak:'Racha de juego creada',achievementVeteran:'25 partidas completadas',achievementDark:'Entró en la Sala Oscura',competitionSeason:'Arena de competición',competitionSubtitle:'Vuelve cada día y sigue avanzando.',streak:'Racha',continuousDays:'días consecutivos',xpReward:'RECOMPENSA XP',whenCompleteToday:'Al completar el día',zivoReward:'RECOMPENSA ZIVO',dailyReward:'Recompensa diaria',weekProgress:'esta semana',competitionClaim:'Reclamar recompensa de hoy',competitionClaimed:'Recompensa de hoy reclamada ✓',competitionComplete:'Completa el día y reclama tu recompensa.',competitionStart:'Empieza el desafío de hoy para crear tu racha.',playerMissions:'MISIONES DEL JUGADOR',todayMissions:'Misiones de hoy',missionsSubtitle:'Complétalas y sube de nivel',missionsDescription:'Las misiones diarias añaden objetivos breves para que cada visita tenga un nuevo motivo para jugar.',missionPlay:'Completa un desafío',missionCorrect:'Consigue 5 respuestas correctas',missionSpeed:'Responde rápido',claim:'Reclamar'",
'fr':"achievementSystem:'SYSTÈME DE SUCCÈS',achievementsTitle:'Succès du joueur',achievementLevel:'Niveau',achievementShare:'Partager la carte du joueur',achievementCopied:'Carte du joueur copiée',achievementFirstStep:'Premier défi',achievementSpeed:'Réponse avant la fin du temps',achievementTenGames:'10 parties terminées',achievementPerfect:'Score parfait dans un défi',achievementStreak:'Série de jeu créée',achievementVeteran:'25 parties terminées',achievementDark:'Entrée dans la Chambre noire',competitionSeason:'Arène de compétition',competitionSubtitle:'Revenez chaque jour pour progresser.',streak:'Série',continuousDays:'jours consécutifs',xpReward:'RÉCOMPENSE XP',whenCompleteToday:'À la fin du jour',zivoReward:'RÉCOMPENSE ZIVO',dailyReward:'Récompense du jour',weekProgress:'cette semaine',competitionClaim:'Réclamer la récompense du jour',competitionClaimed:'Récompense du jour réclamée ✓',competitionComplete:'Terminez la journée puis réclamez votre récompense.',competitionStart:'Commencez le défi du jour pour construire votre série.',playerMissions:'MISSIONS DU JOUEUR',todayMissions:'Missions du jour',missionsSubtitle:'Terminez-les et montez de niveau',missionsDescription:'Les missions quotidiennes ajoutent de petits objectifs pour donner une nouvelle raison de jouer à chaque visite.',missionPlay:'Terminer un défi',missionCorrect:'Obtenir 5 bonnes réponses',missionSpeed:'Répondre rapidement',claim:'Réclamer'",
'fa':"achievementSystem:'سیستم دستاوردها',achievementsTitle:'دستاوردهای بازیکن',achievementLevel:'سطح',achievementShare:'اشتراک‌گذاری کارت بازیکن',achievementCopied:'کارت بازیکن کپی شد',achievementFirstStep:'اولین چالش',achievementSpeed:'پاسخ پیش از پایان زمان',achievementTenGames:'۱۰ بازی تکمیل‌شده',achievementPerfect:'امتیاز کامل در یک چالش',achievementStreak:'ساختن رکورد پیوسته بازی',achievementVeteran:'۲۵ بازی تکمیل‌شده',achievementDark:'ورود به اتاق تاریک',competitionSeason:'میدان رقابت',competitionSubtitle:'هر روز برگردید و پیشرفت کنید.',streak:'رکورد پیوسته',continuousDays:'روز پیاپی',xpReward:'پاداش XP',whenCompleteToday:'با تکمیل امروز',zivoReward:'پاداش ZIVO',dailyReward:'پاداش روزانه',weekProgress:'این هفته',competitionClaim:'دریافت پاداش امروز',competitionClaimed:'پاداش امروز دریافت شد ✓',competitionComplete:'امروز را کامل کنید و سپس پاداش را بگیرید.',competitionStart:'برای ساختن رکورد پیوسته، چالش امروز را شروع کنید.',playerMissions:'ماموریت‌های بازیکن',todayMissions:'ماموریت‌های امروز',missionsSubtitle:'انجام دهید و سطح خود را بالا ببرید',missionsDescription:'ماموریت‌های روزانه هدف‌های کوتاهی اضافه می‌کنند تا هر ورود دلیل تازه‌ای برای بازی داشته باشد.',missionPlay:'یک چالش را کامل کنید',missionCorrect:'۵ پاسخ درست بدهید',missionSpeed:'سریع پاسخ دهید',claim:'دریافت'"
}
lines=[]
for lang,val in keys.items(): lines.append(f"  Object.assign(T.{lang},{{{val}}});")
block='\n'.join(lines)+'\n'
if 'achievementSystem:' not in s:
    s=s.replace(marker,block+marker)
p.write_text(s,encoding='utf8')
