/* ============================================================
   ZIVOZONE V22 — EXPANDED CONTENT BANK
   6 new challenge worlds × 10 questions.
   Every question/choice has AR / EN / ZH / HI / ES.
============================================================ */
(()=>{
  const M=(ar,en,zh,hi,es)=>({ar,en,zh,hi,es});
  const Q=(id,type,q,opts,c,d,answer)=>({id,type,q,a:opts,c,d,answer});
  const B=(id,icon,title,desc,questions)=>({id,icon,title,desc,xp:140,special:false,questions});
  const banks={
    probability:B('probability_v22','🎲',M('مختبر الاحتمالات','Probability Lab','概率实验室','प्रायिकता लैब','Laboratorio de probabilidad'),M('احسب تحت الضغط واكتشف الاحتمال الحقيقي.','Calculate under pressure and find the real probability.','在压力下计算并找到真正的概率。','दबाव में गणना करें और वास्तविक प्रायिकता खोजें।','Calcula bajo presión y descubre la probabilidad real.'),[
      Q('pr22_01','choice',M('عملة عادلة: احتمال ظهور الصورة في رمية واحدة؟','Fair coin: probability of heads on one toss?','公平硬币一次出现正面的概率？','निष्पक्ष सिक्का: एक उछाल में हेड आने की प्रायिकता?','Moneda justa: probabilidad de cara en un lanzamiento?'),[M('25%','25%','25%','25%','25%'),M('50%','50%','50%','50%','50%'),M('75%','75%','75%','75%','75%'),M('100%','100%','100%','100%','100%')],1,1),
      Q('pr22_02','number',M('كيس فيه 3 حمراء و2 زرقاء. كم كرة زرقاء من أصل 5؟ اكتب النسبة المئوية.','A bag has 3 red and 2 blue balls. What percentage are blue?','袋中有3个红球和2个蓝球。蓝球占百分之多少？','एक थैले में 3 लाल और 2 नीली गेंदें हैं। नीली कितने प्रतिशत हैं?','Una bolsa tiene 3 bolas rojas y 2 azules. ¿Qué porcentaje son azules?'),[],4,2,'40'),
      Q('pr22_03','choice',M('رمي نرد عادل: احتمال الحصول على رقم أكبر من 4؟','Fair die: probability of rolling a number greater than 4?','公平骰子：掷出大于4的数字的概率？','निष्पक्ष पासा: 4 से बड़ा अंक आने की प्रायिकता?','Dado justo: probabilidad de obtener un número mayor que 4?'),[M('1/6','1/6','1/6','1/6','1/6'),M('1/3','1/3','1/3','1/3','1/3'),M('1/2','1/2','1/2','1/2','1/2'),M('2/3','2/3','2/3','2/3','2/3')],1,3),
      Q('pr22_04','number',M('من 10 تذاكر، 3 رابحة. احتمال سحب رابحة كنسبة مئوية؟','Out of 10 tickets, 3 win. Winning probability as a percentage?','10张票中3张中奖。中奖概率是多少百分比？','10 टिकटों में 3 विजेता हैं। प्रतिशत प्रायिकता?','De 10 boletos, 3 ganan. ¿Probabilidad de ganar en porcentaje?'),[],3,4,'30'),
      Q('pr22_05','choice',M('إذا كان احتمال حدث 0.2، فما احتمال عدم حدوثه؟','If an event has probability 0.2, what is the probability it does not happen?','事件概率为0.2，不发生的概率是多少？','यदि किसी घटना की प्रायिकता 0.2 है, तो न होने की प्रायिकता?','Si un evento tiene probabilidad 0,2, ¿cuál es la de que no ocurra?'),[M('0.2','0.2','0.2','0.2','0.2'),M('0.5','0.5','0.5','0.5','0.5'),M('0.8','0.8','0.8','0.8','0.8'),M('1.2','1.2','1.2','1.2','1.2')],2,5),
      Q('pr22_06','number',M('رميا نرد مرتين. ما عدد النواتج المرتبة الممكنة؟','Two dice are rolled. How many ordered outcomes are possible?','掷两个骰子，有多少种有序结果？','दो पासे फेंके गए। कितने क्रमित परिणाम संभव हैं?','Se lanzan dos dados. ¿Cuántos resultados ordenados son posibles?'),[],6,6,'36'),
      Q('pr22_07','choice',M('ما احتمال الحصول على مجموع 7 عند رمي نردين؟','Probability of a sum of 7 with two dice?','两个骰子和为7的概率？','दो पासों का योग 7 होने की प्रायिकता?','Probabilidad de sumar 7 con dos dados?'),[M('1/12','1/12','1/12','1/12','1/12'),M('1/6','1/6','1/6','1/6','1/6'),M('1/4','1/4','1/4','1/4','1/4'),M('1/3','1/3','1/3','1/3','1/3')],1,7),
      Q('pr22_08','number',M('في صندوق 4 حمراء و6 زرقاء. تسحب كرة دون إرجاع ثم ثانية. احتمال أن تكون الاثنتان زرقاوين كنسبة مئوية؟','A box has 4 red and 6 blue. Draw two without replacement. Probability both are blue, as a percentage?','盒中4红6蓝，不放回抽两次。两次都是蓝色的概率百分比？','डिब्बे में 4 लाल और 6 नीली। बिना वापसी दो बार। दोनों नीली होने की प्रतिशत प्रायिकता?','Caja con 4 rojas y 6 azules. Dos extracciones sin reemplazo. ¿Probabilidad de dos azules en %?'),[],8,8,'33.3333333333'),
      Q('pr22_09','choice',M('إذا كان احتمال الفوز 1/4 في كل محاولة مستقلة، هل احتمال الفوز مرتين متتاليتين يساوي 1/8؟','If winning probability is 1/4 each independent attempt, is winning twice in a row 1/8?','每次独立获胜概率为1/4，连续两次获胜是否为1/8？','यदि हर स्वतंत्र प्रयास में जीत 1/4 है, लगातार दो जीत क्या 1/8 हैं?','Si ganar es 1/4 en cada intento independiente, ¿ganar dos veces seguidas es 1/8?'),[M('نعم، هو 1/16','No, it is 1/16','不，是1/16','नहीं, 1/16 है','No, es 1/16'),M('نعم','Yes','是','हाँ','Sí'),M('لا يمكن حسابه','Cannot calculate','无法计算','गणना नहीं कर सकते','No se puede calcular'),M('1/4','1/4','1/4','1/4','1/4')],0,9),
      Q('pr22_10','number',M('ثلاثة أحداث مستقلة احتمال كل منها 1/2. احتمال حدوثها كلها كنسبة مئوية؟','Three independent events each have probability 1/2. Probability all occur, in percent?','三个独立事件概率都为1/2，全部发生的概率百分比？','तीन स्वतंत्र घटनाओं की प्रायिकता 1/2 है। तीनों होने की प्रतिशत प्रायिकता?','Tres eventos independientes tienen probabilidad 1/2 cada uno. ¿Probabilidad de que ocurran todos en %?'),[],10,10,'12.5')
    ]),
    lateral:B('lateral_v22','🌀',M('مختبر التفكير الجانبي','Lateral Thinking Lab','横向思维实验室','लेटरल थिंकिंग लैब','Laboratorio de pensamiento lateral'),M('أسئلة تكسر الافتراضات وتختبر زاوية النظر.','Questions that break assumptions and test perspective.','打破假设，测试视角。','धारणाएँ तोड़ने और दृष्टिकोण जाँचने वाले प्रश्न।','Preguntas que rompen supuestos y prueban la perspectiva.'),[
      Q('lt22_01','choice',M('رجل ولد عام 2005 وتوفي عام 2005 بعمر 80. كيف؟','A man was born in 2005 and died in 2005 aged 80. How?','一名男子出生于2005年，2005年去世，享年80岁。怎么可能？','एक आदमी 2005 में पैदा हुआ और 2005 में 80 वर्ष की आयु में मर गया। कैसे?','Un hombre nació en 2005 y murió en 2005 a los 80 años. ¿Cómo?'),[M('السنوات ليست سنوات الميلاد','The numbers are not years','这些数字不是年份','ये वर्ष नहीं हैं','No son años'),M('خطأ رياضي','Math error','数学错误','गणितीय त्रुटि','Error matemático'),M('سافر عبر الزمن','Time travel','时间旅行','समय यात्रा','Viajó en el tiempo'),M('مستحيل','Impossible','不可能','असंभव','Imposible')],0,1),
      Q('lt22_02','number',M('لديك 5 تفاحات، أخذتَ 2. كم تفاحة أصبحت معك؟','You have 5 apples and take 2. How many do you have?','你有5个苹果，拿走2个。你有几个？','आपके पास 5 सेब हैं और 2 लेते हैं। आपके पास कितने हैं?','Tienes 5 manzanas y tomas 2. ¿Cuántas tienes?'),[],2,2,'2'),
      Q('lt22_03','choice',M('طبيب أعطى مريضًا 3 حبات وقال: خذ حبة كل نصف ساعة. كم يستغرق أخذها كلها؟','A doctor gives 3 pills: take one every half hour. How long to take all?','医生给3粒药，每半小时一粒。全部吃完需要多久？','डॉक्टर ने 3 गोलियाँ दीं: हर आधे घंटे में एक। कुल समय?','Un médico da 3 pastillas: una cada media hora. ¿Cuánto tardas en tomarlas todas?'),[M('30 دقيقة','30 minutes','30分钟','30 मिनट','30 minutos'),M('60 دقيقة','60 minutes','60分钟','60 मिनट','60 minutos'),M('90 دقيقة','90 minutes','90分钟','90 मिनट','90 minutos'),M('120 دقيقة','120 minutes','120分钟','120 मिनट','120 minutos')],1,3),
      Q('lt22_04','number',M('قطار كهربائي يسير شمالًا. الرياح جنوبًا. إلى أين يتجه الدخان؟','An electric train travels north. Wind blows south. Where does the smoke go?','电动火车向北行驶，风向南吹。烟往哪里走？','एक इलेक्ट्रिक ट्रेन उत्तर जाती है, हवा दक्षिण। धुआँ किस ओर जाएगा?','Un tren eléctrico va al norte y el viento al sur. ¿Hacia dónde va el humo?'),[],4,4,'0'),
      Q('lt22_05','choice',M('ما الشيء الذي كلما أخذت منه كبر؟','What gets bigger the more you take from it?','什么东西你拿走越多反而越大？','क्या चीज़ जितना निकालो उतनी बड़ी होती जाती है?','¿Qué se hace más grande cuanto más quitas?'),[M('الحفرة','A hole','洞','गड्ढा','Un agujero'),M('الكتاب','A book','书','किताब','Un libro'),M('الظل','A shadow','影子','छाया','Una sombra'),M('الوقت','Time','时间','समय','El tiempo')],0,5),
      Q('lt22_06','number',M('في سباق تجاوزت الشخص صاحب المركز الثاني. ما مركزك الآن؟','In a race you pass the person in second place. What place are you now?','比赛中你超过第二名。你现在第几名？','दौड़ में आपने दूसरे स्थान वाले को पार किया। अब आप किस स्थान पर हैं?','En una carrera adelantas al segundo. ¿Qué posición ocupas?'),[],6,6,'2'),
      Q('lt22_07','choice',M('أم لديها 4 بنات، لكل بنت أخ واحد. كم طفلًا لديها؟','A mother has 4 daughters, each has one brother. How many children?','一位母亲有4个女儿，每个女儿有一个哥哥。共有几个孩子？','एक माँ की 4 बेटियाँ हैं, हर बेटी का एक भाई है। कुल बच्चे?','Una madre tiene 4 hijas y cada una tiene un hermano. ¿Cuántos hijos?'),[M('4','4','4','4','4'),M('5','5','5','5','5'),M('8','8','8','8','8'),M('9','9','9','9','9')],1,7),
      Q('lt22_08','number',M('ساعة تشير إلى 3:00. كم درجة بين العقربين؟','A clock shows 3:00. What angle is between the hands?','时钟显示3:00，两针夹角多少度？','घड़ी 3:00 दिखाती है। सुइयों के बीच कोण?','Un reloj marca las 3:00. ¿Qué ángulo hay entre las agujas?'),[],8,8,'90'),
      Q('lt22_09','choice',M('شيء له مدن بلا بيوت وأنهار بلا ماء. ما هو؟','It has cities without houses and rivers without water. What is it?','它有城市却没有房屋，有河流却没有水。是什么？','इसमें शहर हैं पर घर नहीं, नदियाँ हैं पर पानी नहीं। क्या है?','Tiene ciudades sin casas y ríos sin agua. ¿Qué es?'),[M('خريطة','A map','地图','मानचित्र','Un mapa'),M('كتاب','A book','书','किताब','Un libro'),M('مرآة','A mirror','镜子','आईना','Un espejo'),M('طائرة','A plane','飞机','विमान','Un avión')],0,9),
      Q('lt22_10','number',M('لديك كوب ماء كامل. أضفت إليه ماءً دون أن يفيض. كيف؟','A glass is full of water. You add water without overflow. How?','杯子装满水，你再加水却不溢出。怎么做？','गिलास पानी से भरा है। बिना छलके पानी जोड़ें। कैसे?','Un vaso está lleno de agua. Añades agua sin que rebose. ¿Cómo?'),[],10,10,'ثلج')
    ]),
    code:B('code_v22','💻',M('مختبر الشيفرة','Code Lab','代码实验室','कोड लैब','Laboratorio de código'),M('أنماط وخوارزميات وتفكير برمجي دون كتابة كود.','Patterns, algorithms and programming thinking without coding.','模式、算法与编程思维，无需写代码。','कोड लिखे बिना पैटर्न, एल्गोरिदम और प्रोग्रामिंग सोच।','Patrones, algoritmos y pensamiento de programación sin escribir código.'),[
      Q('cd22_01','choice',M('ما ناتج: 2 + 3 × 4؟','What is 2 + 3 × 4?','2 + 3 × 4 等于多少？','2 + 3 × 4 का परिणाम?','¿Cuánto es 2 + 3 × 4?'),[M('20','20','20','20','20'),M('14','14','14','14','14'),M('24','24','24','24','24'),M('10','10','10','10','10')],1,1),
      Q('cd22_02','number',M('إذا كان x=5، فما قيمة 2x+7؟','If x=5, what is 2x+7?','若x=5，2x+7是多少？','यदि x=5, 2x+7 कितना है?','Si x=5, ¿cuánto es 2x+7?'),[],2,2,'17'),
      Q('cd22_03','choice',M('ما الذي تفعله الحلقة التي تتكرر 5 مرات؟','What does a loop repeated 5 times do?','循环重复5次会做什么？','5 बार दोहराया गया लूप क्या करता है?','¿Qué hace un bucle repetido 5 veces?'),[M('تنفذ التعليمات 5 مرات','Executes instructions 5 times','执行指令5次','निर्देश 5 बार चलाता है','Ejecuta instrucciones 5 veces'),M('تحذف البرنامج','Deletes the program','删除程序','प्रोग्राम हटाता है','Borra el programa'),M('توقف الجهاز','Stops the device','停止设备','डिवाइस रोकता है','Detiene el dispositivo'),M('تغير اللغة','Changes language','更改语言','भाषा बदलता है','Cambia el idioma')],0,3),
      Q('cd22_04','number',M('تسلسل يبدأ 1 ثم كل مرة يضرب ×2. ما العنصر السادس؟','Sequence starts 1 and doubles each time. What is the sixth term?','序列从1开始，每次乘2。第六项是多少？','क्रम 1 से शुरू होकर हर बार दोगुना होता है। छठा पद?','Secuencia empieza en 1 y se duplica. ¿Sexto término?'),[],4,4,'32'),
      Q('cd22_05','choice',M('إذا كانت قيمة الشرط false، ماذا يحدث لفرع if؟','If a condition is false, what happens to the if branch?','如果条件为false，if分支会怎样？','यदि शर्त false है, if शाखा का क्या होगा?','Si la condición es false, ¿qué pasa con la rama if?'),[M('ينفذ','Executes','执行','चलता है','Se ejecuta'),M('لا ينفذ','Does not execute','不执行','नहीं चलता','No se ejecuta'),M('يعيد التشغيل','Restarts','重启','पुनः शुरू','Reinicia'),M('يحذف نفسه','Deletes itself','删除自身','खुद को हटाता है','Se elimina')],1,5),
      Q('cd22_06','number',M('إذا كانت القائمة [4,7,9]، ما فهرس العنصر الأول في البرمجة الصفرية؟','For [4,7,9], what is the first element index in zero-based programming?','对于[4,7,9]，零基索引第一个元素是多少？','[4,7,9] में zero-based पहला index क्या है?','Para [4,7,9], ¿índice del primer elemento con base cero?'),[],6,6,'0'),
      Q('cd22_07','choice',M('خوارزمية تبحث في قائمة مرتبة بتقسيمها إلى نصفين تُسمى؟','An algorithm that searches a sorted list by halving it is called?','在有序列表中不断二分查找的算法叫？','क्रमबद्ध सूची को आधा-आधा करके खोजने का एल्गोरिद्म?','Algoritmo que busca en lista ordenada dividiéndola por la mitad?'),[M('بحث ثنائي','Binary search','二分查找','बाइनरी सर्च','Búsqueda binaria'),M('فقاعي','Bubble sort','冒泡排序','बबल सॉर्ट','Ordenamiento burbuja'),M('تشفير','Encryption','加密','एन्क्रिप्शन','Cifrado'),M('ضغط','Compression','压缩','कम्प्रेशन','Compresión')],0,7),
      Q('cd22_08','number',M('كم مرة تنفذ حلقة for من 0 إلى أقل من 5؟','How many times does a for-loop from 0 while less than 5 run?','for循环从0运行到小于5，共执行几次？','0 से 5 से कम तक for-loop कितनी बार चलता है?','¿Cuántas veces corre un for de 0 mientras sea menor que 5?'),[],8,8,'5'),
      Q('cd22_09','choice',M('أي بنية تناسب حفظ أزواج مفتاح/قيمة؟','Which structure fits key/value pairs?','哪种结构适合保存键/值对？','key/value जोड़ों के लिए कौन-सी संरचना?','¿Qué estructura sirve para pares clave/valor?'),[M('قاموس','Dictionary','字典','डिक्शनरी','Diccionario'),M('مكدس فقط','Stack only','仅栈','केवल स्टैक','Solo pila'),M('طابور فقط','Queue only','仅队列','केवल कतार','Solo cola'),M('مصفوفة صورة','Image array','图像数组','इमेज ऐरे','Matriz de imagen')],0,9),
      Q('cd22_10','number',M('إذا كان لديك 8 عناصر وتقسم المجموعة إلى نصفين مرتين، كم مجموعة نهائية؟','With 8 items, split the group in half twice. How many final groups?','8个元素连续二分两次，最终有多少组？','8 तत्वों को दो बार आधा करें। अंतिम समूह कितने?','Con 8 elementos, divides el grupo por la mitad dos veces. ¿Cuántos grupos finales?'),[],10,10,'4')
    ]),
    language:B('language_v22','🔤',M('مختبر اللغة','Language Lab','语言实验室','भाषा लैब','Laboratorio de idiomas'),M('دقة لغوية وأنماط كلمات وتركيز على التفاصيل.','Language precision, word patterns and detail focus.','语言精度、词语模式与细节注意力。','भाषाई सटीकता, शब्द पैटर्न और विवरण पर ध्यान।','Precisión lingüística, patrones de palabras y atención al detalle.'),[
      Q('la22_01','choice',M('أي كلمة مكتوبة بشكل صحيح؟','Which word is spelled correctly?','哪个单词拼写正确？','कौन-सा शब्द सही वर्तनी वाला है?','¿Qué palabra está escrita correctamente?'),[M('مسؤول','مسؤول','مسؤول','مسؤول','مسؤول'),M('مسئول','مسئول','مسئول','مسئول','مسئول'),M('مسوؤل','مسوؤل','مسوؤل','مسوؤل','مسوؤل'),M('مسئؤل','مسئؤل','مسئؤل','مسئؤل','مسئؤل')],0,1),
      Q('la22_02','number',M('كم حرفًا في كلمة ZIVOZONE؟','How many letters are in ZIVOZONE?','ZIVOZONE有多少个字母？','ZIVOZONE में कितने अक्षर हैं?','¿Cuántas letras tiene ZIVOZONE?'),[],2,2,'8'),
      Q('la22_03','choice',M('أي كلمة عكس معنى “سريع”؟','Which word is opposite of “fast”?','“快”的反义词是什么？','“तेज़” का विलोम क्या है?','¿Cuál es lo contrario de “rápido”?'),[M('بطيء','Slow','慢','धीमा','Lento'),M('قوي','Strong','强','मज़बूत','Fuerte'),M('ذكي','Smart','聪明','बुद्धिमान','Inteligente'),M('قصير','Short','短','छोटा','Corto')],0,3),
      Q('la22_04','number',M('في الجملة: “ذهب اللاعب إلى الملعب”، كم كلمة؟','In “The player went to the field”, how many words?','句子“球员去了球场”有几个词？','“खिलाड़ी मैदान गया” में कितने शब्द?','En “El jugador fue al campo”, ¿cuántas palabras?'),[],4,4,'5'),
      Q('la22_05','choice',M('أي ترتيب أبجدي صحيح: باب، بحر، بيت؟','Which alphabetical order is correct: باب، بحر، بيت?','哪个字母顺序正确：باب、بحر、بيت？','कौन-सा वर्णक्रम सही है: باب، بحر، بيت?','¿Qué orden alfabético es correcto: باب، بحر، بيت?'),[M('باب، بحر، بيت','باب، بحر، بيت','باب، بحر، بيت','باب، بحر، بيت','باب، بحر، بيت'),M('بحر، باب، بيت','بحر، باب، بيت','بحر، باب، بيت','بحر، باب، بيت','بحر، باب، بيت'),M('بيت، بحر، باب','بيت، بحر، باب','بيت، بحر، باب','بيت، بحر، باب','بيت، بحر، باب'),M('بيت، باب، بحر','بيت، باب، بحر','بيت، باب، بحر','بيت، باب، بحر','بيت، باب، بحر')],0,5),
      Q('la22_06','number',M('كم مقطعًا صوتيًا تقريبًا في كلمة “مكتبة”؟','Approximately how many syllables in “مكتبة”?','阿拉伯词“مكتبة”大约几个音节？','“मكتبة” में लगभग कितने syllables हैं?','¿Aproximadamente cuántas sílabas tiene “مكتبة”?'),[],6,6,'3'),
      Q('la22_07','choice',M('أي جملة تدل على المستقبل؟','Which sentence indicates the future?','哪句话表示将来？','कौन-सा वाक्य भविष्य बताता है?','¿Qué frase indica futuro?'),[M('سألعب غدًا','I will play tomorrow','我明天会踢球','मैं कल खेलूँगा','Jugaré mañana'),M('لعبت أمس','I played yesterday','我昨天踢了球','मैं कल खेला','Jugué ayer'),M('ألعب الآن','I play now','我现在踢球','मैं अभी खेलता हूँ','Juego ahora'),M('كنت ألعب','I was playing','我当时在踢球','मैं खेल रहा था','Estaba jugando')],0,7),
      Q('la22_08','number',M('إذا حذفت أول وآخر حرف من كلمة “سلام”، كم حرفًا يبقى؟','If you remove the first and last letters of “سلام”, how many remain?','删除“سلام”的首尾字母后剩几个字母？','“سلام” के पहला और आखिरी अक्षर हटाने पर कितने बचते हैं?','Si quitas la primera y última letra de “سلام”, ¿cuántas quedan?'),[],8,8,'2'),
      Q('la22_09','choice',M('أي كلمة تحتوي على حرفين متشابهين متتاليين؟','Which word contains two identical consecutive letters?','哪个词有两个连续相同字母？','किस शब्द में लगातार दो समान अक्षर हैं?','¿Qué palabra tiene dos letras iguales consecutivas?'),[M('مدرسة','School','学校','स्कूल','Escuela'),M('مرّ','Passed','经过','गुज़रा','Pasó'),M('كتاب','Book','书','किताब','Libro'),M('قلم','Pen','笔','कलम','Bolígrafo')],1,9),
      Q('la22_10','number',M('كم حرفًا عربيًا في كلمة “ذكاء”؟','How many Arabic letters are in “ذكاء”?','“ذكاء”有几个阿拉伯字母？','“ذكاء” में कितने अरबी अक्षर हैं?','¿Cuántas letras árabes hay en “ذكاء”?'),[],10,10,'4')
    ]),
    memory:B('memory_v22','🧠',M('ذاكرة النخبة','Elite Memory','精英记忆','एलीट मेमोरी','Memoria élite'),M('ذاكرة متسلسلة مع ضغط زمني وتصاعد تدريجي.','Sequential memory under time pressure with rising difficulty.','时间压力下的序列记忆，难度逐步上升。','समय दबाव में क्रमिक स्मृति और बढ़ती कठिनाई।','Memoria secuencial bajo presión con dificultad creciente.'),[
      Q('me22_01','choice',M('احفظ: 4-9-2. ما الرقم الأوسط؟','Remember 4-9-2. What is the middle number?','记住4-9-2。中间数字是多少？','4-9-2 याद रखें। बीच का अंक?','Recuerda 4-9-2. ¿Cuál es el número central?'),[M('4','4','4','4','4'),M('9','9','9','9','9'),M('2','2','2','2','2'),M('6','6','6','6','6')],1,1),
      Q('me22_02','number',M('احفظ: 7-1-8-3. ما الرقم الأخير؟','Remember 7-1-8-3. What is the last number?','记住7-1-8-3。最后一个数字？','7-1-8-3 याद रखें। आखिरी अंक?','Recuerda 7-1-8-3. ¿Último número?'),[],2,2,'3'),
      Q('me22_03','choice',M('احفظ: قمر، بحر، باب. ما الكلمة الأولى؟','Remember: moon, sea, door. What is first?','记住：月亮、海、门。第一个是什么？','याद रखें: चाँद, समुद्र, दरवाज़ा। पहला?','Recuerda: luna, mar, puerta. ¿Cuál es la primera?'),[M('بحر','Sea','海','समुद्र','Mar'),M('قمر','Moon','月亮','चाँद','Luna'),M('باب','Door','门','दरवाज़ा','Puerta'),M('لا أعرف','I do not know','不知道','पता नहीं','No sé')],1,3),
      Q('me22_04','number',M('احفظ: 2-5-9-4-7. ما مجموع أول وآخر رقم؟','Remember 2-5-9-4-7. Sum first and last.','记住2-5-9-4-7。首尾数字之和？','2-5-9-4-7 याद रखें। पहला+अंतिम?','Recuerda 2-5-9-4-7. Suma primero y último.'),[],4,4,'9'),
      Q('me22_05','choice',M('السلسلة: أحمر، أزرق، أخضر، أصفر، أسود. ما اللون الثالث؟','Sequence: red, blue, green, yellow, black. Third?','序列：红、蓝、绿、黄、黑。第三个？','क्रम: लाल, नीला, हरा, पीला, काला। तीसरा?','Secuencia: rojo, azul, verde, amarillo, negro. ¿Tercero?'),[M('أحمر','Red','红','लाल','Rojo'),M('أزرق','Blue','蓝','नीला','Azul'),M('أخضر','Green','绿','हरा','Verde'),M('أسود','Black','黑','काला','Negro')],2,5),
      Q('me22_06','number',M('احفظ: 6-3-8-1-5. ما حاصل ضرب الأول والأخير؟','Remember 6-3-8-1-5. Product of first and last?','记住6-3-8-1-5。首尾相乘？','6-3-8-1-5 याद रखें। पहला×अंतिम?','Recuerda 6-3-8-1-5. Producto del primero y último?'),[],6,6,'30'),
      Q('me22_07','choice',M('احفظ الترتيب: 3، 8، 1، 6، 4، 9. أي رقم جاء قبل 6؟','Remember 3,8,1,6,4,9. Which came before 6?','记住3、8、1、6、4、9。6前面是什么？','3,8,1,6,4,9 याद रखें। 6 से पहले?','Recuerda 3,8,1,6,4,9. ¿Cuál estaba antes del 6?'),[M('1','1','1','1','1'),M('8','8','8','8','8'),M('4','4','4','4','4'),M('9','9','9','9','9')],0,7),
      Q('me22_08','number',M('احفظ: 9-2-7-4-6-1. ما الفرق بين الرقمين الأول والثاني؟','Remember 9-2-7-4-6-1. Difference between first and second?','记住9-2-7-4-6-1。前两个数字之差？','9-2-7-4-6-1 याद रखें। पहले-दूसरे का अंतर?','Recuerda 9-2-7-4-6-1. Diferencia entre primero y segundo?'),[],8,8,'7'),
      Q('me22_09','choice',M('احفظ: 5، 1، 9، 2، 8، 3، 7. ما الرقم الذي كان بين 9 و8؟','Remember 5,1,9,2,8,3,7. What was between 9 and 8?','记住5、1、9、2、8、3、7。9和8之间是什么？','5,1,9,2,8,3,7 याद रखें। 9 और 8 के बीच?','Recuerda 5,1,9,2,8,3,7. ¿Qué estaba entre 9 y 8?'),[M('1','1','1','1','1'),M('2','2','2','2','2'),M('3','3','3','3','3'),M('5','5','5','5','5')],1,9),
      Q('me22_10','number',M('احفظ: 4،7،2،9،1،8. اضرب الرقم الثاني في الخامس.','Remember 4,7,2,9,1,8. Multiply the second by the fifth.','记住4、7、2、9、1、8。第二个乘第五个。','4,7,2,9,1,8 याद रखें। दूसरा×पाँचवाँ?','Recuerda 4,7,2,9,1,8. Multiplica segundo por quinto.'),[],10,10,'7')
    ]),
    visual:B('visual_v22','👁️',M('مختبر الأنماط البصرية','Visual Pattern Lab','视觉模式实验室','विज़ुअल पैटर्न लैब','Laboratorio de patrones visuales'),M('أنماط ورموز واتجاهات تُحل بالعقل لا بالحدس.','Patterns, symbols and directions solved by reasoning.','通过推理解决模式、符号和方向。','तर्क से पैटर्न, प्रतीक और दिशा हल करें।','Patrones, símbolos y direcciones mediante razonamiento.'),[
      Q('vi22_01','choice',M('أكمل: ▲ ● ▲ ● ▲ ؟','Complete: ▲ ● ▲ ● ▲ ?','完成：▲ ● ▲ ● ▲ ؟','पूरा करें: ▲ ● ▲ ● ▲ ?','Completa: ▲ ● ▲ ● ▲ ?'),[M('■','■','■','■','■'),M('●','●','●','●','●'),M('▲','▲','▲','▲','▲'),M('◆','◆','◆','◆','◆')],1,1),
      Q('vi22_02','choice',M('أكمل: ↑ → ↓ ← ↑ ؟','Complete: ↑ → ↓ ← ↑ ?','完成：↑ → ↓ ← ↑ ؟','पूरा करें: ↑ → ↓ ← ↑ ?','Completa: ↑ → ↓ ← ↑ ?'),[M('↑','↑','↑','↑','↑'),M('→','→','→','→','→'),M('↓','↓','↓','↓','↓'),M('←','←','←','←','←')],1,2),
      Q('vi22_03','number',M('إذا كان النمط يتكرر كل 4 رموز، ما موضع الرمز نفسه عند 9؟','If a pattern repeats every 4 symbols, what position matches position 9?','模式每4个符号重复，第9位与第几位相同？','यदि पैटर्न हर 4 प्रतीक दोहरता है, 9वाँ किससे मेल खाता है?','Si un patrón se repite cada 4 símbolos, ¿qué posición coincide con la 9?'),[],2,3,'1'),
      Q('vi22_04','choice',M('أكمل: 1 مربع، 2 دائرة، 3 مربع، 4 دائرة، 5 ؟','Complete: 1 square, 2 circle, 3 square, 4 circle, 5 ?','完成：1方形、2圆形、3方形、4圆形、5？','पूरा करें: 1 वर्ग, 2 वृत्त, 3 वर्ग, 4 वृत्त, 5 ?','Completa: 1 cuadrado, 2 círculo, 3 cuadrado, 4 círculo, 5 ?'),[M('مربع','Square','方形','वर्ग','Cuadrado'),M('دائرة','Circle','圆形','वृत्त','Círculo'),M('مثلث','Triangle','三角形','त्रिकोण','Triángulo'),M('نجمة','Star','星形','सितारा','Estrella')],0,4),
      Q('vi22_05','number',M('مكعب له 6 أوجه. كم وجهًا يلامس وجهًا واحدًا محددًا؟','A cube has 6 faces. How many faces touch one chosen face?','立方体有6个面。一个指定面接触几个面？','घन के 6 फलक हैं। एक चुने हुए फलक को कितने फलक छूते हैं?','Un cubo tiene 6 caras. ¿Cuántas tocan una cara elegida?'),[],4,5,'4'),
      Q('vi22_06','choice',M('إذا دُوّر السهم ↑ نصف دورة، يصبح؟','Rotate ↑ by half a turn. It becomes?','将↑旋转半圈，会变成？','↑ को आधा घुमाने पर क्या बनेगा?','Gira ↑ media vuelta. ¿En qué se convierte?'),[M('↑','↑','↑','↑','↑'),M('→','→','→','→','→'),M('↓','↓','↓','↓','↓'),M('←','←','←','←','←')],2,6),
      Q('vi22_07','number',M('شبكة 3×3 فيها 9 خلايا. كم خلية تقع على الحافة؟','A 3×3 grid has 9 cells. How many cells are on the edge?','3×3网格有9格，边缘有多少格？','3×3 ग्रिड में 9 खाने हैं। किनारे पर कितने?','Una cuadrícula 3×3 tiene 9 celdas. ¿Cuántas están en el borde?'),[],6,7,'8'),
      Q('vi22_08','choice',M('ما الشكل المختلف: مثلث، مربع، دائرة، مستطيل؟','Which shape is different: triangle, square, circle, rectangle?','哪个形状不同：三角形、正方形、圆形、矩形？','कौन-सा आकार अलग है: त्रिकोण, वर्ग, वृत्त, आयत?','¿Qué forma es diferente: triángulo, cuadrado, círculo, rectángulo?'),[M('مثلث','Triangle','三角形','त्रिकोण','Triángulo'),M('مربع','Square','正方形','वर्ग','Cuadrado'),M('دائرة','Circle','圆形','वृत्त','Círculo'),M('مستطيل','Rectangle','矩形','आयत','Rectángulo')],2,8),
      Q('vi22_09','number',M('كم محور تناظر للمربع؟','How many lines of symmetry does a square have?','正方形有多少条对称轴？','वर्ग में सममिति की कितनी रेखाएँ हैं?','¿Cuántos ejes de simetría tiene un cuadrado?'),[],9,9,'4'),
      Q('vi22_10','choice',M('نمط: ●، ●●، ●●●، ؟ كم دائرة؟','Pattern: ●, ●●, ●●●, ? How many circles next?','模式：●、●●、●●●、？下一项几个圆？','पैटर्न: ●, ●●, ●●●, ? अगली बार कितने वृत्त?','Patrón: ●, ●●, ●●●, ¿cuántos círculos siguen?'),[M('3','3','3','3','3'),M('4','4','4','4','4'),M('5','5','5','5','5'),M('6','6','6','6','6')],1,10)
    ])
  };
  window.ZIVOZONE_V22_BANK=banks;
  const C=window.ZIVOZONE_CHALLENGES;
  if(C){Object.values(banks).forEach(b=>{C[b.id]=b});const old=C.getAll;C.getAll=()=>{const arr=old?old.call(C):[];return arr.concat(Object.values(banks)).filter((x,i,a)=>x&&x.id&&a.findIndex(y=>y.id===x.id)===i)};}
})();
